# v7 CPU finalization — frozen cap-15 confirmation (direct / crash-safe style)

This is the **same frozen finalization experiment** as the previous `v7_cpu_finalize` notebook, but it runs **directly in the notebook kernel** rather than generating and launching a separate Python runner.

Nothing in the experiment specification is changed:

- architecture: current v7 shared 4×50 ReLU trunk + maturity Softplus heads;
- loss: ordinary MSE;
- rolling recalibration: **exactly 15 SDE updates/day**;
- 10 SDE optimizer steps + 10 control-variate/hedge optimizer steps per update;
- 4,096 paths/step, 400 sampled contracts/step;
- learning rates unchanged from v7 (`1e-4` SDE, `1e-3` hedge);
- no patience-based stopping and no same-day checkpoint reranking;
- primary confirmation evaluation: **100k common-shock paths**;
- untouched test period: **Mar-8 → Mar-28**, 14 next-day transitions;
- robustness pass: **400k antithetic paths**, evaluation only, with the same trained models.

The only change is execution/visibility: the run is in-kernel, with notebook-native progress bars around the long loops. Existing checkpoints/results are still reused.

In [1]:
import gc
import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm

import search_pipeline as sp
import overnight_fixed_runner as ofr
from audit_v7 import load_notebook_environment

# Load the exact v7 notebook environment used by the frozen-search code.
ns = load_notebook_environment()

# Keep the frozen CPU-final settings exactly as before.
ns["FINAL_PATH_CHUNK"] = 2000
torch.set_num_threads(3)

# Make the crash-safe notebook's stage messages coexist cleanly with tqdm.
ns["stage_log"] = lambda message: tqdm.write(str(message))

print("Frozen v7 environment loaded directly into this kernel.")
print("PyTorch threads:", torch.get_num_threads())
print("FINAL_PATH_CHUNK:", ns["FINAL_PATH_CHUNK"])
print("Run root:", sp.RUN_ROOT)

Device: cpu | PyTorch threads: 1
Compute profile: cpu | transitions: 5
Calibration universe: all filtered OTM
Objective: plain contract-level raw price MSE (spot-scaled)
Main budget: 100 SDE phases | polish: 30 SDE phases
LR: 0.0001 | hedge LR: 0.001 | scheduler: none
Early stop: 10 SDE phases without a new raw-RMSE best
options : one_month_spx_option_price.csv
forwards: one_month_spx_forward_price.csv
spot    : one_month_spx_security_price.csv
rates   : one_month_spx_zero_coupon_yield_curve.csv
Complete cleaned quotes: 192031
OTM calibration observations: 91930
Trading dates: 20
Expiry/settlement slices: 809
Anchor selected/train/validation: 4304 3443 861
Anchor selected as fraction of filtered OTM: 100.0%
Anchor maturities train/validation: 36 36
Anchor training contracts: 3443
Anchor maturity heads: 36
Anchor simulation steps: 129
Frozen v7 environment loaded directly into this kernel.
PyTorch threads: 3
FINAL_PATH_CHUNK: 2000
Run root: C:\Users\Startklar\ICL\NDEs\Codes\NSDE\GPT_NSDE_work\v7_long_run_workspace\search_runs

## Helpers

These are orchestration-only helpers. They do not change model architecture, training loss, optimizer settings, seeds, data selection, path counts, or evaluation definitions.

In [2]:
def load_model(checkpoint_path):
    payload = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    model = ns["MaturityHeadNeuralLocalVol"](payload["boundaries"]).cpu()
    model.load_state_dict(payload["final_model_state"], strict=True)
    model.eval()
    sp.set_grad(model, False)
    return model


def existing_row(path, date):
    if not path.exists():
        return None
    df = pd.read_csv(path)
    if "date" not in df.columns:
        return None
    df["date"] = pd.to_datetime(df["date"])
    hit = df.loc[df["date"] == pd.Timestamp(date)]
    return None if hit.empty else hit.iloc[-1].to_dict()


def pooled(df):
    n = df["otm_n"].to_numpy(float)
    p = df["otm_pricing_RMSE"].to_numpy(float)
    h = df["otm_NLV_hedge_RMSE"].to_numpy(float)
    m = df["otm_market_delta_hedge_RMSE"].to_numpy(float)
    out = {
        "otm_n": int(n.sum()),
        "pooled_otm_pricing_RMSE": float(np.sqrt(np.sum(n * p**2) / np.sum(n))),
        "pooled_otm_NLV_hedge_RMSE": float(np.sqrt(np.sum(n * h**2) / np.sum(n))),
        "pooled_otm_market_delta_hedge_RMSE": float(np.sqrt(np.sum(n * m**2) / np.sum(n))),
    }
    if "otm_pricing_MAE" in df.columns:
        out["weighted_otm_pricing_MAE"] = float(
            np.sum(n * df["otm_pricing_MAE"].to_numpy(float)) / np.sum(n)
        )
    return out


def train_fixed_endpoint_visible(**kwargs):
    """Run the unchanged fixed-endpoint trainer while exposing optimizer-step progress.

    The wrapper temporarily instruments simulate_estimators only to advance tqdm.
    The original numerical function is called unchanged and restored immediately after.
    """
    updates = int(kwargs["updates"])
    steps_per_phase = int(ns.get("STEPS_PER_PHASE", 10))
    total_steps = updates * 2 * steps_per_phase
    date = pd.Timestamp(kwargs["date"])

    original_simulate = ns.get("simulate_estimators")
    bar = tqdm(
        total=total_steps,
        desc=f"Train {date:%Y-%m-%d} | cap-{updates} MSE",
        unit="opt-step",
        dynamic_ncols=True,
        mininterval=0.5,
        leave=True,
    )

    if original_simulate is not None:
        def visible_simulate(*args, **inner_kwargs):
            result = original_simulate(*args, **inner_kwargs)
            bar.update(1)
            return result
        ns["simulate_estimators"] = visible_simulate

    try:
        result = ofr.train_fixed_endpoint(ns, **kwargs)
        if bar.n < bar.total:
            # If the trainer resumed internally or uses a path not routed through
            # simulate_estimators, complete only the display bar; this changes no computation.
            bar.update(bar.total - bar.n)
        return result
    finally:
        if original_simulate is not None:
            ns["simulate_estimators"] = original_simulate
        bar.close()

## 1. Frozen 14-transition confirmation — 15 updates/day, 100k evaluation

This is the primary untouched test. Re-running the cell is safe: completed endpoint checkpoints and completed transition summaries are reused.

In [3]:
# Exact same development anchor as the previous finalization notebook.
dev_dir = sp.RUN_ROOT / "capped15_endpoint"
dev_last = dev_dir / "20240307_checkpoint.pt"
if not dev_last.exists():
    raise FileNotFoundError(
        f"Missing {dev_last}. Run/extract the completed capped15_endpoint development branch first."
    )

out = sp.RUN_ROOT / "frozen_test_capped15_endpoint"
out.mkdir(parents=True, exist_ok=True)

previous = load_model(dev_last)
previous_date = pd.Timestamp("2024-03-07")

trading_dates = [pd.Timestamp(x) for x in ns["trading_dates"]]
start = trading_dates.index(pd.Timestamp("2024-03-08"))
training_dates = trading_dates[start:-1]
target_dates = trading_dates[start+1:]
assert len(training_dates) == 14 and len(target_dates) == 14

partial_summary = out / "unseen_summary_partial.csv"
partial_meta = out / "training_metadata_partial.csv"
summaries, metadata = [], []

transitions = list(zip(training_dates, target_dates))
outer = tqdm(
    transitions,
    total=len(transitions),
    desc="Frozen test: train + 100k eval",
    unit="transition",
    dynamic_ncols=True,
    mininterval=0.5,
    leave=True,
)

for index, (date, target) in enumerate(outer, start=1):
    outer.set_description(f"Frozen {date:%m-%d} → {target:%m-%d}")
    outer.set_postfix_str("checkpoint")

    cp = out / f"{date:%Y%m%d}_checkpoint.pt"
    old_summary = existing_row(partial_summary, date)
    old_meta = existing_row(partial_meta, date)

    if cp.exists():
        outer.set_postfix_str("reuse trained endpoint")
        tqdm.write(f"[reuse checkpoint] {date.date()}")
        model = load_model(cp)
        ctx = None

        if old_meta is None:
            payload = torch.load(cp, map_location="cpu", weights_only=False)
            meta = {
                "date": date,
                "endpoint_update": int(payload["endpoint_update"]),
                "objective": "mse",
                "paths_per_step": 4096,
                "elapsed_seconds": np.nan,
            }
            del payload
        else:
            meta = old_meta
    else:
        outer.set_postfix_str("training: cap-15 MSE")
        tqdm.write(f"\nTRAIN {date.date()} → {target.date()} | fixed cap-15 MSE")

        model, ctx, meta = train_fixed_endpoint_visible(
            name="frozen_test_capped15_endpoint",
            objective="mse",
            updates=15,
            paths_per_step=4096,
            seed_offset=0,
            date=date,
            previous_model=previous,
            previous_date=previous_date,
            output_dir=out,
        )

    if old_summary is None:
        outer.set_postfix_str("100k common-shock eval")
        tqdm.write(f"EVAL 100k {date.date()} → {target.date()}")

        cfg = sp.SearchConfig(
            name="frozen_test_capped15_endpoint",
            eval_paths=100000,
            seed_offset=0,
        )
        summary = sp.evaluate_one_transition(
            ns, model, date, target, cfg, out, index
        )
    else:
        outer.set_postfix_str("reuse 100k result")
        tqdm.write(f"[reuse 100k] {date.date()} → {target.date()}")
        summary = old_summary

    summaries.append(summary)
    metadata.append(meta)

    # Same crash-safe partial persistence as before.
    pd.DataFrame(summaries).to_csv(partial_summary, index=False)
    pd.DataFrame(metadata).to_csv(partial_meta, index=False)

    if ctx is not None:
        del ctx
    del previous
    previous = model
    previous_date = date
    gc.collect()

outer.close()

primary_summary = pd.DataFrame(summaries)
primary_summary.to_csv(out / "unseen_summary.csv", index=False)
pd.DataFrame(metadata).to_csv(out / "training_metadata.csv", index=False)

primary_pooled = pooled(primary_summary)
pd.DataFrame([
    {"variant": "frozen_test_capped15_endpoint", **primary_pooled}
]).to_csv(out / "pooled_summary.csv", index=False)

print("\nPRIMARY FROZEN CONFIRMATION COMPLETE")
print(primary_pooled)

Frozen test: train + 100k eval:   0%|          | 0/14 [00:00<?, ?transition/s]

TRAIN 2024-03-08 → 2024-03-11 | fixed cap-15 MSE

Train 2024-03-08 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-07 -> 2024-03-08: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y
[resume] frozen_test_capped15_endpoint 2024-03-08 from update 8/15

[checkpoint] frozen_test_capped15_endpoint 2024-03-08 10/15 | train=4.20858e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-08 12/15 | train=4.82354e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-08 14/15 | train=3.51599e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-08 15/15 | train=3.52638e-07

EVAL 100k 2024-03-08 → 2024-03-11

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8520.15path/s]

transition: begin
transition AM=0: simulation begin, rows=6554

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:11<00:00, 8851.93path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=191
transition AM=0: payoff begin T=0.043835616438356165, contracts=191
transition AM=0: payoff begin T=0.04657534246575343, contracts=248
transition AM=0: payoff begin T=0.057534246575342465, contracts=188
transition AM=0: payoff begin T=0.06027397260273973, contracts=173
transition AM=0: payoff begin T=0.06301369863013699, contracts=175
transition AM=0: payoff begin T=0.06575342465753424, contracts=152
transition AM=0: payoff begin T=0.0684931506849315, contracts=249
transition AM=0: payoff begin T=0.07671232876712329, contracts=115
transition AM=0: payoff begin T=0.07945205479452055, contracts=112
transition AM=0: payoff begin T=0.0821917808219178, contracts=107
transition AM=0: payoff begin T=0.08493150684931507, contracts=99
transition AM=0: payoff begin T=0.08767123287671233, contracts=264
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10684931506849316, contracts=349
transition AM=0: payoff begin T=0.12602739726027398, contracts=179
transition AM=0: payoff begin T=0.136986301369863, contracts=384
transition AM=0: payoff begin T=0.14520547945205478, contracts=118
transition AM=0: payoff begin T=0.18356164383561643, contracts=401
transition AM=0: payoff begin T=0.2219178082191781, contracts=475
transition AM=0: payoff begin T=0.27945205479452057, contracts=350
transition AM=0: payoff begin T=0.29863013698630136, contracts=568
transition AM=0: payoff begin T=0.3561643835616438, contracts=370
transition AM=0: payoff begin T=0.38904109589041097, contracts=323
transition AM=0: payoff begin T=0.4712328767123288, contracts=298
transition AM=0: payoff begin T=0.5561643835616439, contracts=153
transition AM=0: payoff begin T=0.8082191780821918, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2796

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9485.75path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.10684931506849316, contracts=348
transition AM=1: payoff begin T=0.18356164383561643, contracts=415
transition AM=1: payoff begin T=0.27945205479452057, contracts=459
transition AM=1: payoff begin T=0.3561643835616438, contracts=370
transition AM=1: payoff begin T=0.4328767123287671, contracts=359
transition AM=1: payoff begin T=0.5287671232876713, contracts=149
transition AM=1: payoff begin T=0.6054794520547945, contracts=121
transition AM=1: payoff begin T=0.6821917808219178, contracts=123
transition AM=1: payoff begin T=0.7780821917808219, contracts=141
transition AM=1: payoff begin T=0.8547945205479452, contracts=145
transition AM=1: payoff begin T=0.9506849315068493, contracts=166
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-11 → 2024-03-12 | fixed cap-15 MSE

Train 2024-03-11 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-08 -> 2024-03-11: 36 heads | elapsed=0.00822y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 2/15 | train=4.55823e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 4/15 | train=5.25825e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 6/15 | train=5.50783e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 8/15 | train=3.96421e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 10/15 | train=3.50536e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 12/15 | train=4.93921e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 14/15 | train=4.28129e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-11 15/15 | train=3.09428e-07

EVAL 100k 2024-03-11 → 2024-03-12

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8970.35path/s]

transition: begin
transition AM=0: simulation begin, rows=6317

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9526.33path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=176
transition AM=0: payoff begin T=0.043835616438356165, contracts=221
transition AM=0: payoff begin T=0.0547945205479452, contracts=176
transition AM=0: payoff begin T=0.057534246575342465, contracts=165
transition AM=0: payoff begin T=0.06027397260273973, contracts=178
transition AM=0: payoff begin T=0.06301369863013699, contracts=155
transition AM=0: payoff begin T=0.06575342465753424, contracts=231
transition AM=0: payoff begin T=0.07397260273972603, contracts=111
transition AM=0: payoff begin T=0.07671232876712329, contracts=108
transition AM=0: payoff begin T=0.07945205479452055, contracts=105
transition AM=0: payoff begin T=0.0821917808219178, contracts=104
transition AM=0: payoff begin T=0.08493150684931507, contracts=246
transition AM=0: payoff begin T=0.09315068493150686, contracts=93
transition AM=0: payoff begin T=0.0958904109589041, contracts=64
transition AM=0: payoff begin T=0.09863013698630137, contracts=67
transition AM=0: payoff begin T=0.10410958904109589, contracts=320
transition AM=0: payoff begin T=0.1232876712328767, contracts=269
transition AM=0: payoff begin T=0.13424657534246576, contracts=359
transition AM=0: payoff begin T=0.14246575342465753, contracts=173
transition AM=0: payoff begin T=0.18082191780821918, contracts=381
transition AM=0: payoff begin T=0.2191780821917808, contracts=456
transition AM=0: payoff begin T=0.27671232876712326, contracts=339
transition AM=0: payoff begin T=0.2958904109589041, contracts=544
transition AM=0: payoff begin T=0.35342465753424657, contracts=358
transition AM=0: payoff begin T=0.3863013698630137, contracts=320
transition AM=0: payoff begin T=0.4684931506849315, contracts=296
transition AM=0: payoff begin T=0.5534246575342465, contracts=149
transition AM=0: payoff begin T=0.8054794520547945, contracts=153
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2697

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9680.12path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.10410958904109589, contracts=321
transition AM=1: payoff begin T=0.18082191780821918, contracts=395
transition AM=1: payoff begin T=0.27671232876712326, contracts=443
transition AM=1: payoff begin T=0.35342465753424657, contracts=358
transition AM=1: payoff begin T=0.4301369863013699, contracts=354
transition AM=1: payoff begin T=0.5260273972602739, contracts=145
transition AM=1: payoff begin T=0.6027397260273972, contracts=117
transition AM=1: payoff begin T=0.6794520547945205, contracts=121
transition AM=1: payoff begin T=0.7753424657534247, contracts=138
transition AM=1: payoff begin T=0.852054794520548, contracts=143
transition AM=1: payoff begin T=0.947945205479452, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-12 → 2024-03-13 | fixed cap-15 MSE

Train 2024-03-12 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-11 -> 2024-03-12: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 2/15 | train=7.4211e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 4/15 | train=5.88611e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 6/15 | train=4.65237e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 8/15 | train=4.02162e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 10/15 | train=3.61448e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 12/15 | train=3.1504e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 14/15 | train=3.02765e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-12 15/15 | train=3.69115e-07

EVAL 100k 2024-03-12 → 2024-03-13

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8827.19path/s]

transition: begin
transition AM=0: simulation begin, rows=6281

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9449.88path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=222
transition AM=0: payoff begin T=0.052054794520547946, contracts=178
transition AM=0: payoff begin T=0.0547945205479452, contracts=165
transition AM=0: payoff begin T=0.057534246575342465, contracts=178
transition AM=0: payoff begin T=0.06027397260273973, contracts=158
transition AM=0: payoff begin T=0.06301369863013699, contracts=233
transition AM=0: payoff begin T=0.07123287671232877, contracts=148
transition AM=0: payoff begin T=0.07397260273972603, contracts=108
transition AM=0: payoff begin T=0.07671232876712329, contracts=105
transition AM=0: payoff begin T=0.07945205479452055, contracts=104
transition AM=0: payoff begin T=0.0821917808219178, contracts=249
transition AM=0: payoff begin T=0.09041095890410959, contracts=97
transition AM=0: payoff begin T=0.09315068493150686, contracts=64
transition AM=0: payoff begin T=0.0958904109589041, contracts=67
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10136986301369863, contracts=323
transition AM=0: payoff begin T=0.12054794520547946, contracts=271
transition AM=0: payoff begin T=0.13150684931506848, contracts=363
transition AM=0: payoff begin T=0.13972602739726028, contracts=175
transition AM=0: payoff begin T=0.1780821917808219, contracts=383
transition AM=0: payoff begin T=0.21643835616438356, contracts=459
transition AM=0: payoff begin T=0.273972602739726, contracts=337
transition AM=0: payoff begin T=0.29315068493150687, contracts=545
transition AM=0: payoff begin T=0.3506849315068493, contracts=359
transition AM=0: payoff begin T=0.3835616438356164, contracts=321
transition AM=0: payoff begin T=0.4657534246575342, contracts=297
transition AM=0: payoff begin T=0.5506849315068493, contracts=150
transition AM=0: payoff begin T=0.8027397260273973, contracts=154
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2720

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9458.76path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.10136986301369863, contracts=325
transition AM=1: payoff begin T=0.1780821917808219, contracts=396
transition AM=1: payoff begin T=0.273972602739726, contracts=444
transition AM=1: payoff begin T=0.3506849315068493, contracts=359
transition AM=1: payoff begin T=0.4273972602739726, contracts=354
transition AM=1: payoff begin T=0.5232876712328767, contracts=145
transition AM=1: payoff begin T=0.6, contracts=117
transition AM=1: payoff begin T=0.6767123287671233, contracts=121
transition AM=1: payoff begin T=0.7726027397260274, contracts=154
transition AM=1: payoff begin T=0.8493150684931506, contracts=143
transition AM=1: payoff begin T=0.9452054794520548, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-13 → 2024-03-14 | fixed cap-15 MSE

Train 2024-03-13 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-12 -> 2024-03-13: 35 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 2/15 | train=5.48652e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 4/15 | train=5.76126e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 6/15 | train=4.81592e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 8/15 | train=5.05667e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 10/15 | train=3.45344e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 12/15 | train=3.35122e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 14/15 | train=4.34759e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-13 15/15 | train=3.50703e-07

EVAL 100k 2024-03-13 → 2024-03-14

Same-day MC: 100%|██████████| 100000/100000 [00:14<00:00, 6794.08path/s]

transition: begin
transition AM=0: simulation begin, rows=6100

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:13<00:00, 7673.82path/s]

transition AM=0: simulation returned; terminal storage=10.3 MiB
transition AM=0: payoff begin T=0.049315068493150684, contracts=177
transition AM=0: payoff begin T=0.052054794520547946, contracts=177
transition AM=0: payoff begin T=0.0547945205479452, contracts=179
transition AM=0: payoff begin T=0.057534246575342465, contracts=160
transition AM=0: payoff begin T=0.06027397260273973, contracts=218
transition AM=0: payoff begin T=0.0684931506849315, contracts=174
transition AM=0: payoff begin T=0.07123287671232877, contracts=151
transition AM=0: payoff begin T=0.07397260273972603, contracts=104
transition AM=0: payoff begin T=0.07671232876712329, contracts=103
transition AM=0: payoff begin T=0.07945205479452055, contracts=237
transition AM=0: payoff begin T=0.08767123287671233, contracts=106
transition AM=0: payoff begin T=0.09041095890410959, contracts=94
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=65
transition AM=0: payoff begin T=0.09863013698630137, contracts=299
transition AM=0: payoff begin T=0.1178082191780822, contracts=281
transition AM=0: payoff begin T=0.12876712328767123, contracts=345
transition AM=0: payoff begin T=0.136986301369863, contracts=184
transition AM=0: payoff begin T=0.17534246575342466, contracts=372
transition AM=0: payoff begin T=0.2136986301369863, contracts=448
transition AM=0: payoff begin T=0.27123287671232876, contracts=320
transition AM=0: payoff begin T=0.29041095890410956, contracts=541
transition AM=0: payoff begin T=0.34794520547945207, contracts=359
transition AM=0: payoff begin T=0.38082191780821917, contracts=326
transition AM=0: payoff begin T=0.46301369863013697, contracts=305
transition AM=0: payoff begin T=0.547945205479452, contracts=153
transition AM=0: payoff begin T=0.8, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2681

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9697.84path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.09863013698630137, contracts=303
transition AM=1: payoff begin T=0.17534246575342466, contracts=384
transition AM=1: payoff begin T=0.27123287671232876, contracts=428
transition AM=1: payoff begin T=0.34794520547945207, contracts=357
transition AM=1: payoff begin T=0.4246575342465753, contracts=358
transition AM=1: payoff begin T=0.5205479452054794, contracts=148
transition AM=1: payoff begin T=0.5972602739726027, contracts=119
transition AM=1: payoff begin T=0.673972602739726, contracts=121
transition AM=1: payoff begin T=0.7698630136986301, contracts=156
transition AM=1: payoff begin T=0.8465753424657534, contracts=143
transition AM=1: payoff begin T=0.9424657534246575, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-14 → 2024-03-15 | fixed cap-15 MSE

Train 2024-03-14 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-13 -> 2024-03-14: 35 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 2/15 | train=1.03355e-06

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 4/15 | train=4.50711e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 6/15 | train=4.75025e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 8/15 | train=3.29669e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 10/15 | train=3.15596e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 12/15 | train=3.40354e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 14/15 | train=4.49567e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-14 15/15 | train=3.52692e-07

EVAL 100k 2024-03-14 → 2024-03-15

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 9049.93path/s]

transition: begin
transition AM=0: simulation begin, rows=6659

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9518.57path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.04657534246575343, contracts=175
transition AM=0: payoff begin T=0.049315068493150684, contracts=177
transition AM=0: payoff begin T=0.052054794520547946, contracts=179
transition AM=0: payoff begin T=0.0547945205479452, contracts=160
transition AM=0: payoff begin T=0.057534246575342465, contracts=214
transition AM=0: payoff begin T=0.06575342465753424, contracts=175
transition AM=0: payoff begin T=0.0684931506849315, contracts=152
transition AM=0: payoff begin T=0.07123287671232877, contracts=149
transition AM=0: payoff begin T=0.07397260273972603, contracts=103
transition AM=0: payoff begin T=0.07671232876712329, contracts=232
transition AM=0: payoff begin T=0.08493150684931507, contracts=106
transition AM=0: payoff begin T=0.08767123287671233, contracts=98
transition AM=0: payoff begin T=0.09041095890410959, contracts=96
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=303
transition AM=0: payoff begin T=0.10410958904109589, contracts=98
transition AM=0: payoff begin T=0.11506849315068493, contracts=281
transition AM=0: payoff begin T=0.12602739726027398, contracts=346
transition AM=0: payoff begin T=0.13424657534246576, contracts=184
transition AM=0: payoff begin T=0.1726027397260274, contracts=376
transition AM=0: payoff begin T=0.21095890410958903, contracts=448
transition AM=0: payoff begin T=0.2684931506849315, contracts=324
transition AM=0: payoff begin T=0.2876712328767123, contracts=549
transition AM=0: payoff begin T=0.3452054794520548, contracts=365
transition AM=0: payoff begin T=0.3780821917808219, contracts=329
transition AM=0: payoff begin T=0.42191780821917807, contracts=358
transition AM=0: payoff begin T=0.4602739726027397, contracts=304
transition AM=0: payoff begin T=0.5452054794520548, contracts=154
transition AM=0: payoff begin T=0.7972602739726027, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2704

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9602.53path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.0958904109589041, contracts=302
transition AM=1: payoff begin T=0.1726027397260274, contracts=388
transition AM=1: payoff begin T=0.2684931506849315, contracts=432
transition AM=1: payoff begin T=0.3452054794520548, contracts=362
transition AM=1: payoff begin T=0.42191780821917807, contracts=358
transition AM=1: payoff begin T=0.5178082191780822, contracts=151
transition AM=1: payoff begin T=0.5945205479452055, contracts=119
transition AM=1: payoff begin T=0.6712328767123288, contracts=123
transition AM=1: payoff begin T=0.7671232876712328, contracts=160
transition AM=1: payoff begin T=0.8438356164383561, contracts=145
transition AM=1: payoff begin T=0.9397260273972603, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-15 → 2024-03-18 | fixed cap-15 MSE

Train 2024-03-15 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-14 -> 2024-03-15: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 2/15 | train=4.34121e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 4/15 | train=2.88192e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 6/15 | train=5.97625e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 8/15 | train=3.38048e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 10/15 | train=2.80662e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 12/15 | train=2.11522e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 14/15 | train=3.21409e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-15 15/15 | train=5.39137e-07

EVAL 100k 2024-03-15 → 2024-03-18

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8913.35path/s]

transition: begin
transition AM=0: simulation begin, rows=6486

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9603.23path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=167
transition AM=0: payoff begin T=0.043835616438356165, contracts=172
transition AM=0: payoff begin T=0.04657534246575343, contracts=163
transition AM=0: payoff begin T=0.049315068493150684, contracts=203
transition AM=0: payoff begin T=0.057534246575342465, contracts=172
transition AM=0: payoff begin T=0.06027397260273973, contracts=153
transition AM=0: payoff begin T=0.06301369863013699, contracts=148
transition AM=0: payoff begin T=0.06575342465753424, contracts=143
transition AM=0: payoff begin T=0.0684931506849315, contracts=225
transition AM=0: payoff begin T=0.07671232876712329, contracts=105
transition AM=0: payoff begin T=0.07945205479452055, contracts=97
transition AM=0: payoff begin T=0.0821917808219178, contracts=95
transition AM=0: payoff begin T=0.08493150684931507, contracts=93
transition AM=0: payoff begin T=0.08767123287671233, contracts=292
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=61
transition AM=0: payoff begin T=0.10684931506849316, contracts=275
transition AM=0: payoff begin T=0.1178082191780822, contracts=332
transition AM=0: payoff begin T=0.12602739726027398, contracts=183
transition AM=0: payoff begin T=0.1643835616438356, contracts=370
transition AM=0: payoff begin T=0.20273972602739726, contracts=443
transition AM=0: payoff begin T=0.2602739726027397, contracts=330
transition AM=0: payoff begin T=0.27945205479452057, contracts=544
transition AM=0: payoff begin T=0.336986301369863, contracts=365
transition AM=0: payoff begin T=0.3698630136986301, contracts=328
transition AM=0: payoff begin T=0.4136986301369863, contracts=312
transition AM=0: payoff begin T=0.4520547945205479, contracts=304
transition AM=0: payoff begin T=0.536986301369863, contracts=155
transition AM=0: payoff begin T=0.7890410958904109, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2692

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9797.65path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.08767123287671233, contracts=291
transition AM=1: payoff begin T=0.1643835616438356, contracts=381
transition AM=1: payoff begin T=0.2602739726027397, contracts=437
transition AM=1: payoff begin T=0.336986301369863, contracts=363
transition AM=1: payoff begin T=0.4136986301369863, contracts=358
transition AM=1: payoff begin T=0.5095890410958904, contracts=151
transition AM=1: payoff begin T=0.5863013698630137, contracts=119
transition AM=1: payoff begin T=0.663013698630137, contracts=123
transition AM=1: payoff begin T=0.7589041095890411, contracts=160
transition AM=1: payoff begin T=0.8356164383561644, contracts=145
transition AM=1: payoff begin T=0.9315068493150684, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-18 → 2024-03-19 | fixed cap-15 MSE

Train 2024-03-18 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-15 -> 2024-03-18: 36 heads | elapsed=0.00822y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 2/15 | train=5.8399e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 4/15 | train=6.74107e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 6/15 | train=3.48269e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 8/15 | train=3.34644e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 10/15 | train=3.40468e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 12/15 | train=2.91678e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 14/15 | train=2.18624e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-18 15/15 | train=2.33221e-07

EVAL 100k 2024-03-18 → 2024-03-19

Same-day MC: 100%|██████████| 100000/100000 [00:10<00:00, 9221.56path/s]

transition: begin
transition AM=0: simulation begin, rows=6514

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9505.45path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=166
transition AM=0: payoff begin T=0.043835616438356165, contracts=163
transition AM=0: payoff begin T=0.04657534246575343, contracts=192
transition AM=0: payoff begin T=0.0547945205479452, contracts=183
transition AM=0: payoff begin T=0.057534246575342465, contracts=159
transition AM=0: payoff begin T=0.06027397260273973, contracts=174
transition AM=0: payoff begin T=0.06301369863013699, contracts=155
transition AM=0: payoff begin T=0.06575342465753424, contracts=220
transition AM=0: payoff begin T=0.07397260273972603, contracts=103
transition AM=0: payoff begin T=0.07671232876712329, contracts=103
transition AM=0: payoff begin T=0.07945205479452055, contracts=102
transition AM=0: payoff begin T=0.0821917808219178, contracts=100
transition AM=0: payoff begin T=0.08493150684931507, contracts=282
transition AM=0: payoff begin T=0.09315068493150686, contracts=96
transition AM=0: payoff begin T=0.0958904109589041, contracts=61
transition AM=0: payoff begin T=0.09863013698630137, contracts=61
transition AM=0: payoff begin T=0.10410958904109589, contracts=273
transition AM=0: payoff begin T=0.11506849315068493, contracts=324
transition AM=0: payoff begin T=0.1232876712328767, contracts=183
transition AM=0: payoff begin T=0.16164383561643836, contracts=363
transition AM=0: payoff begin T=0.2, contracts=440
transition AM=0: payoff begin T=0.25753424657534246, contracts=422
transition AM=0: payoff begin T=0.27671232876712326, contracts=584
transition AM=0: payoff begin T=0.33424657534246577, contracts=358
transition AM=0: payoff begin T=0.36712328767123287, contracts=325
transition AM=0: payoff begin T=0.410958904109589, contracts=311
transition AM=0: payoff begin T=0.44931506849315067, contracts=302
transition AM=0: payoff begin T=0.5342465753424658, contracts=152
transition AM=0: payoff begin T=0.7863013698630137, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2940

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9854.70path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.08493150684931507, contracts=281
transition AM=1: payoff begin T=0.16164383561643836, contracts=373
transition AM=1: payoff begin T=0.25753424657534246, contracts=432
transition AM=1: payoff begin T=0.33424657534246577, contracts=430
transition AM=1: payoff begin T=0.410958904109589, contracts=355
transition AM=1: payoff begin T=0.5068493150684932, contracts=334
transition AM=1: payoff begin T=0.5835616438356165, contracts=148
transition AM=1: payoff begin T=0.6602739726027397, contracts=125
transition AM=1: payoff begin T=0.7561643835616438, contracts=157
transition AM=1: payoff begin T=0.8328767123287671, contracts=143
transition AM=1: payoff begin T=0.9287671232876712, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-19 → 2024-03-20 | fixed cap-15 MSE

Train 2024-03-19 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-18 -> 2024-03-19: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 2/15 | train=6.40663e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 4/15 | train=7.51086e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 6/15 | train=4.08761e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 8/15 | train=4.38271e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 10/15 | train=3.88843e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 12/15 | train=4.08934e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 14/15 | train=3.46972e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-19 15/15 | train=3.29847e-07

EVAL 100k 2024-03-19 → 2024-03-20

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8936.37path/s]

transition: begin
transition AM=0: simulation begin, rows=5989

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9613.91path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=124
transition AM=0: payoff begin T=0.043835616438356165, contracts=150
transition AM=0: payoff begin T=0.052054794520547946, contracts=145
transition AM=0: payoff begin T=0.0547945205479452, contracts=134
transition AM=0: payoff begin T=0.057534246575342465, contracts=148
transition AM=0: payoff begin T=0.06027397260273973, contracts=144
transition AM=0: payoff begin T=0.06301369863013699, contracts=192
transition AM=0: payoff begin T=0.07123287671232877, contracts=138
transition AM=0: payoff begin T=0.07397260273972603, contracts=98
transition AM=0: payoff begin T=0.07671232876712329, contracts=97
transition AM=0: payoff begin T=0.07945205479452055, contracts=95
transition AM=0: payoff begin T=0.0821917808219178, contracts=240
transition AM=0: payoff begin T=0.09041095890410959, contracts=91
transition AM=0: payoff begin T=0.09315068493150686, contracts=59
transition AM=0: payoff begin T=0.0958904109589041, contracts=60
transition AM=0: payoff begin T=0.09863013698630137, contracts=62
transition AM=0: payoff begin T=0.10136986301369863, contracts=247
transition AM=0: payoff begin T=0.11232876712328767, contracts=282
transition AM=0: payoff begin T=0.12054794520547946, contracts=174
transition AM=0: payoff begin T=0.1589041095890411, contracts=334
transition AM=0: payoff begin T=0.19726027397260273, contracts=413
transition AM=0: payoff begin T=0.2547945205479452, contracts=396
transition AM=0: payoff begin T=0.273972602739726, contracts=545
transition AM=0: payoff begin T=0.3315068493150685, contracts=345
transition AM=0: payoff begin T=0.3643835616438356, contracts=320
transition AM=0: payoff begin T=0.40821917808219177, contracts=351
transition AM=0: payoff begin T=0.4465753424657534, contracts=301
transition AM=0: payoff begin T=0.5315068493150685, contracts=148
transition AM=0: payoff begin T=0.7835616438356164, contracts=156
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2792

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9308.03path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.0821917808219178, contracts=235
transition AM=1: payoff begin T=0.1589041095890411, contracts=339
transition AM=1: payoff begin T=0.2547945205479452, contracts=402
transition AM=1: payoff begin T=0.3315068493150685, contracts=415
transition AM=1: payoff begin T=0.40821917808219177, contracts=351
transition AM=1: payoff begin T=0.5041095890410959, contracts=330
transition AM=1: payoff begin T=0.5808219178082191, contracts=145
transition AM=1: payoff begin T=0.6575342465753424, contracts=121
transition AM=1: payoff begin T=0.7534246575342466, contracts=155
transition AM=1: payoff begin T=0.8301369863013699, contracts=139
transition AM=1: payoff begin T=0.9260273972602739, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-20 → 2024-03-21 | fixed cap-15 MSE

Train 2024-03-20 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-19 -> 2024-03-20: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 2/15 | train=4.8434e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 4/15 | train=5.92973e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 6/15 | train=6.01147e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 8/15 | train=5.22071e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 10/15 | train=2.65753e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 12/15 | train=1.96997e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 14/15 | train=2.39122e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-20 15/15 | train=2.61582e-07

EVAL 100k 2024-03-20 → 2024-03-21

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 9038.44path/s]

transition: begin
transition AM=0: simulation begin, rows=6103

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9590.30path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=147
transition AM=0: payoff begin T=0.049315068493150684, contracts=138
transition AM=0: payoff begin T=0.052054794520547946, contracts=143
transition AM=0: payoff begin T=0.0547945205479452, contracts=146
transition AM=0: payoff begin T=0.057534246575342465, contracts=151
transition AM=0: payoff begin T=0.06027397260273973, contracts=193
transition AM=0: payoff begin T=0.0684931506849315, contracts=148
transition AM=0: payoff begin T=0.07123287671232877, contracts=142
transition AM=0: payoff begin T=0.07397260273972603, contracts=100
transition AM=0: payoff begin T=0.07671232876712329, contracts=101
transition AM=0: payoff begin T=0.07945205479452055, contracts=242
transition AM=0: payoff begin T=0.08767123287671233, contracts=95
transition AM=0: payoff begin T=0.09041095890410959, contracts=91
transition AM=0: payoff begin T=0.09315068493150686, contracts=61
transition AM=0: payoff begin T=0.0958904109589041, contracts=62
transition AM=0: payoff begin T=0.09863013698630137, contracts=249
transition AM=0: payoff begin T=0.1095890410958904, contracts=284
transition AM=0: payoff begin T=0.1178082191780822, contracts=173
transition AM=0: payoff begin T=0.136986301369863, contracts=108
transition AM=0: payoff begin T=0.15616438356164383, contracts=335
transition AM=0: payoff begin T=0.19452054794520549, contracts=420
transition AM=0: payoff begin T=0.25205479452054796, contracts=397
transition AM=0: payoff begin T=0.27123287671232876, contracts=553
transition AM=0: payoff begin T=0.3287671232876712, contracts=345
transition AM=0: payoff begin T=0.36164383561643837, contracts=321
transition AM=0: payoff begin T=0.4054794520547945, contracts=353
transition AM=0: payoff begin T=0.4438356164383562, contracts=301
transition AM=0: payoff begin T=0.5287671232876713, contracts=149
transition AM=0: payoff begin T=0.7808219178082192, contracts=155
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2801

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9822.48path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.07945205479452055, contracts=237
transition AM=1: payoff begin T=0.15616438356164383, contracts=340
transition AM=1: payoff begin T=0.25205479452054796, contracts=403
transition AM=1: payoff begin T=0.3287671232876712, contracts=416
transition AM=1: payoff begin T=0.4054794520547945, contracts=353
transition AM=1: payoff begin T=0.5013698630136987, contracts=331
transition AM=1: payoff begin T=0.5780821917808219, contracts=146
transition AM=1: payoff begin T=0.6547945205479452, contracts=121
transition AM=1: payoff begin T=0.7506849315068493, contracts=155
transition AM=1: payoff begin T=0.8273972602739726, contracts=139
transition AM=1: payoff begin T=0.9232876712328767, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-21 → 2024-03-22 | fixed cap-15 MSE

Train 2024-03-21 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-20 -> 2024-03-21: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 2/15 | train=7.30279e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 4/15 | train=4.89837e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 6/15 | train=5.33353e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 8/15 | train=3.76753e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 10/15 | train=2.59652e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 12/15 | train=2.79906e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 14/15 | train=2.58905e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-21 15/15 | train=2.94852e-07

EVAL 100k 2024-03-21 → 2024-03-22

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8894.81path/s]

transition: begin
transition AM=0: simulation begin, rows=6650

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9537.52path/s]

transition AM=0: simulation returned; terminal storage=11.1 MiB
transition AM=0: payoff begin T=0.04657534246575343, contracts=170
transition AM=0: payoff begin T=0.049315068493150684, contracts=167
transition AM=0: payoff begin T=0.052054794520547946, contracts=187
transition AM=0: payoff begin T=0.0547945205479452, contracts=171
transition AM=0: payoff begin T=0.057534246575342465, contracts=217
transition AM=0: payoff begin T=0.06575342465753424, contracts=179
transition AM=0: payoff begin T=0.0684931506849315, contracts=161
transition AM=0: payoff begin T=0.07123287671232877, contracts=173
transition AM=0: payoff begin T=0.07397260273972603, contracts=113
transition AM=0: payoff begin T=0.07671232876712329, contracts=277
transition AM=0: payoff begin T=0.08493150684931507, contracts=107
transition AM=0: payoff begin T=0.08767123287671233, contracts=102
transition AM=0: payoff begin T=0.09041095890410959, contracts=99
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=277
transition AM=0: payoff begin T=0.10410958904109589, contracts=100
transition AM=0: payoff begin T=0.10684931506849316, contracts=317
transition AM=0: payoff begin T=0.11506849315068493, contracts=185
transition AM=0: payoff begin T=0.13424657534246576, contracts=113
transition AM=0: payoff begin T=0.15342465753424658, contracts=367
transition AM=0: payoff begin T=0.1917808219178082, contracts=435
transition AM=0: payoff begin T=0.2493150684931507, contracts=420
transition AM=0: payoff begin T=0.2684931506849315, contracts=573
transition AM=0: payoff begin T=0.32602739726027397, contracts=357
transition AM=0: payoff begin T=0.3589041095890411, contracts=334
transition AM=0: payoff begin T=0.40273972602739727, contracts=365
transition AM=0: payoff begin T=0.4410958904109589, contracts=310
transition AM=0: payoff begin T=0.5260273972602739, contracts=151
transition AM=0: payoff begin T=0.7780821917808219, contracts=158
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2951

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9805.98path/s]

transition AM=1: simulation returned; terminal storage=4.2 MiB
transition AM=1: payoff begin T=0.07671232876712329, contracts=275
transition AM=1: payoff begin T=0.15342465753424658, contracts=371
transition AM=1: payoff begin T=0.2493150684931507, contracts=427
transition AM=1: payoff begin T=0.32602739726027397, contracts=430
transition AM=1: payoff begin T=0.40273972602739727, contracts=364
transition AM=1: payoff begin T=0.4986301369863014, contracts=357
transition AM=1: payoff begin T=0.5753424657534246, contracts=152
transition AM=1: payoff begin T=0.6520547945205479, contracts=121
transition AM=1: payoff begin T=0.7479452054794521, contracts=155
transition AM=1: payoff begin T=0.8246575342465754, contracts=139
transition AM=1: payoff begin T=0.9205479452054794, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-22 → 2024-03-25 | fixed cap-15 MSE

Train 2024-03-22 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-21 -> 2024-03-22: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 2/15 | train=5.94307e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 4/15 | train=5.17026e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 6/15 | train=6.69948e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 8/15 | train=5.01293e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 10/15 | train=4.06068e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 12/15 | train=3.69797e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 14/15 | train=2.97752e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-22 15/15 | train=3.14761e-07

EVAL 100k 2024-03-22 → 2024-03-25

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8795.49path/s]

transition: begin
transition AM=0: simulation begin, rows=6483

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9535.98path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=158
transition AM=0: payoff begin T=0.043835616438356165, contracts=174
transition AM=0: payoff begin T=0.04657534246575343, contracts=180
transition AM=0: payoff begin T=0.049315068493150684, contracts=204
transition AM=0: payoff begin T=0.057534246575342465, contracts=180
transition AM=0: payoff begin T=0.06027397260273973, contracts=165
transition AM=0: payoff begin T=0.06301369863013699, contracts=177
transition AM=0: payoff begin T=0.06575342465753424, contracts=161
transition AM=0: payoff begin T=0.0684931506849315, contracts=257
transition AM=0: payoff begin T=0.07671232876712329, contracts=108
transition AM=0: payoff begin T=0.07945205479452055, contracts=104
transition AM=0: payoff begin T=0.0821917808219178, contracts=99
transition AM=0: payoff begin T=0.08493150684931507, contracts=96
transition AM=0: payoff begin T=0.08767123287671233, contracts=265
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=298
transition AM=0: payoff begin T=0.10684931506849316, contracts=185
transition AM=0: payoff begin T=0.12602739726027398, contracts=109
transition AM=0: payoff begin T=0.14520547945205478, contracts=375
transition AM=0: payoff begin T=0.18356164383561643, contracts=421
transition AM=0: payoff begin T=0.2410958904109589, contracts=431
transition AM=0: payoff begin T=0.2602739726027397, contracts=554
transition AM=0: payoff begin T=0.3178082191780822, contracts=358
transition AM=0: payoff begin T=0.3506849315068493, contracts=335
transition AM=0: payoff begin T=0.39452054794520547, contracts=369
transition AM=0: payoff begin T=0.4328767123287671, contracts=314
transition AM=0: payoff begin T=0.5178082191780822, contracts=152
transition AM=0: payoff begin T=0.7698630136986301, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3225

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9497.03path/s]

transition AM=1: simulation returned; terminal storage=4.6 MiB
transition AM=1: payoff begin T=0.0684931506849315, contracts=258
transition AM=1: payoff begin T=0.14520547945205478, contracts=384
transition AM=1: payoff begin T=0.2410958904109589, contracts=438
transition AM=1: payoff begin T=0.3178082191780822, contracts=452
transition AM=1: payoff begin T=0.39452054794520547, contracts=368
transition AM=1: payoff begin T=0.4904109589041096, contracts=361
transition AM=1: payoff begin T=0.5671232876712329, contracts=155
transition AM=1: payoff begin T=0.6438356164383562, contracts=156
transition AM=1: payoff begin T=0.7397260273972602, contracts=161
transition AM=1: payoff begin T=0.8164383561643835, contracts=158
transition AM=1: payoff begin T=0.9123287671232877, contracts=161
transition AM=1: payoff begin T=0.989041095890411, contracts=173
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-25 → 2024-03-26 | fixed cap-15 MSE

Train 2024-03-25 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-22 -> 2024-03-25: 36 heads | elapsed=0.00822y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 2/15 | train=6.53073e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 4/15 | train=2.65109e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 6/15 | train=2.79954e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 8/15 | train=2.30348e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 10/15 | train=4.10419e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 12/15 | train=2.32736e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 14/15 | train=2.01341e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-25 15/15 | train=1.45712e-07

EVAL 100k 2024-03-25 → 2024-03-26

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8794.37path/s]

transition: begin
transition AM=0: simulation begin, rows=6305

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9391.70path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=167
transition AM=0: payoff begin T=0.043835616438356165, contracts=175
transition AM=0: payoff begin T=0.04657534246575343, contracts=194
transition AM=0: payoff begin T=0.0547945205479452, contracts=174
transition AM=0: payoff begin T=0.057534246575342465, contracts=163
transition AM=0: payoff begin T=0.06027397260273973, contracts=173
transition AM=0: payoff begin T=0.06301369863013699, contracts=158
transition AM=0: payoff begin T=0.06575342465753424, contracts=244
transition AM=0: payoff begin T=0.07397260273972603, contracts=107
transition AM=0: payoff begin T=0.07671232876712329, contracts=104
transition AM=0: payoff begin T=0.07945205479452055, contracts=98
transition AM=0: payoff begin T=0.0821917808219178, contracts=96
transition AM=0: payoff begin T=0.08493150684931507, contracts=259
transition AM=0: payoff begin T=0.09315068493150686, contracts=96
transition AM=0: payoff begin T=0.0958904109589041, contracts=290
transition AM=0: payoff begin T=0.09863013698630137, contracts=71
transition AM=0: payoff begin T=0.10410958904109589, contracts=182
transition AM=0: payoff begin T=0.1232876712328767, contracts=108
transition AM=0: payoff begin T=0.14246575342465753, contracts=370
transition AM=0: payoff begin T=0.18082191780821918, contracts=414
transition AM=0: payoff begin T=0.23835616438356164, contracts=430
transition AM=0: payoff begin T=0.25753424657534246, contracts=549
transition AM=0: payoff begin T=0.3150684931506849, contracts=357
transition AM=0: payoff begin T=0.34794520547945207, contracts=334
transition AM=0: payoff begin T=0.3917808219178082, contracts=367
transition AM=0: payoff begin T=0.4301369863013699, contracts=314
transition AM=0: payoff begin T=0.5150684931506849, contracts=152
transition AM=0: payoff begin T=0.7671232876712328, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3207

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9324.52path/s]

transition AM=1: simulation returned; terminal storage=4.6 MiB
transition AM=1: payoff begin T=0.06575342465753424, contracts=246
transition AM=1: payoff begin T=0.14246575342465753, contracts=376
transition AM=1: payoff begin T=0.23835616438356164, contracts=433
transition AM=1: payoff begin T=0.3150684931506849, contracts=453
transition AM=1: payoff begin T=0.3917808219178082, contracts=367
transition AM=1: payoff begin T=0.4876712328767123, contracts=362
transition AM=1: payoff begin T=0.5643835616438356, contracts=156
transition AM=1: payoff begin T=0.6410958904109589, contracts=158
transition AM=1: payoff begin T=0.736986301369863, contracts=160
transition AM=1: payoff begin T=0.8136986301369863, contracts=160
transition AM=1: payoff begin T=0.9095890410958904, contracts=162
transition AM=1: payoff begin T=0.9863013698630136, contracts=174
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-26 → 2024-03-27 | fixed cap-15 MSE

Train 2024-03-26 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-25 -> 2024-03-26: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 2/15 | train=6.78028e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 4/15 | train=4.9007e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 6/15 | train=4.242e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 8/15 | train=4.40834e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 10/15 | train=3.38119e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 12/15 | train=3.92009e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 14/15 | train=3.64004e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-26 15/15 | train=2.89434e-07

EVAL 100k 2024-03-26 → 2024-03-27

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8834.28path/s]

transition: begin
transition AM=0: simulation begin, rows=5984

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9665.13path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=153
transition AM=0: payoff begin T=0.043835616438356165, contracts=162
transition AM=0: payoff begin T=0.052054794520547946, contracts=160
transition AM=0: payoff begin T=0.0547945205479452, contracts=154
transition AM=0: payoff begin T=0.057534246575342465, contracts=164
transition AM=0: payoff begin T=0.06027397260273973, contracts=154
transition AM=0: payoff begin T=0.06301369863013699, contracts=221
transition AM=0: payoff begin T=0.07123287671232877, contracts=145
transition AM=0: payoff begin T=0.07397260273972603, contracts=101
transition AM=0: payoff begin T=0.07671232876712329, contracts=98
transition AM=0: payoff begin T=0.07945205479452055, contracts=97
transition AM=0: payoff begin T=0.0821917808219178, contracts=242
transition AM=0: payoff begin T=0.09041095890410959, contracts=95
transition AM=0: payoff begin T=0.09315068493150686, contracts=264
transition AM=0: payoff begin T=0.0958904109589041, contracts=68
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10136986301369863, contracts=174
transition AM=0: payoff begin T=0.12054794520547946, contracts=106
transition AM=0: payoff begin T=0.13972602739726028, contracts=354
transition AM=0: payoff begin T=0.1780821917808219, contracts=398
transition AM=0: payoff begin T=0.2356164383561644, contracts=421
transition AM=0: payoff begin T=0.2547945205479452, contracts=528
transition AM=0: payoff begin T=0.31232876712328766, contracts=349
transition AM=0: payoff begin T=0.3452054794520548, contracts=329
transition AM=0: payoff begin T=0.38904109589041097, contracts=362
transition AM=0: payoff begin T=0.4273972602739726, contracts=311
transition AM=0: payoff begin T=0.5123287671232877, contracts=149
transition AM=0: payoff begin T=0.7643835616438356, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3135

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9581.66path/s]

transition AM=1: simulation returned; terminal storage=4.6 MiB
transition AM=1: payoff begin T=0.06301369863013699, contracts=226
transition AM=1: payoff begin T=0.13972602739726028, contracts=360
transition AM=1: payoff begin T=0.2356164383561644, contracts=424
transition AM=1: payoff begin T=0.31232876712328766, contracts=445
transition AM=1: payoff begin T=0.38904109589041097, contracts=364
transition AM=1: payoff begin T=0.4849315068493151, contracts=359
transition AM=1: payoff begin T=0.5616438356164384, contracts=153
transition AM=1: payoff begin T=0.6383561643835617, contracts=156
transition AM=1: payoff begin T=0.7342465753424657, contracts=158
transition AM=1: payoff begin T=0.810958904109589, contracts=158
transition AM=1: payoff begin T=0.9068493150684932, contracts=160
transition AM=1: payoff begin T=0.9835616438356164, contracts=172
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

TRAIN 2024-03-27 → 2024-03-28 | fixed cap-15 MSE

Train 2024-03-27 | cap-15 MSE:   0%|          | 0/300 [00:00<?, ?opt-step/s]

Warm-start 2024-03-26 -> 2024-03-27: 36 heads | elapsed=0.00274y | median head mismatch=0.00000y

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 2/15 | train=6.3308e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 4/15 | train=3.78151e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 6/15 | train=3.79676e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 8/15 | train=2.24679e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 10/15 | train=3.22971e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 12/15 | train=3.626e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 14/15 | train=3.46984e-07

[checkpoint] frozen_test_capped15_endpoint 2024-03-27 15/15 | train=3.24285e-07

EVAL 100k 2024-03-27 → 2024-03-28

Same-day MC: 100%|██████████| 100000/100000 [00:11<00:00, 8490.97path/s]

transition: begin
transition AM=0: simulation begin, rows=6038

Future-date MC AM=0: 100%|██████████| 100000/100000 [00:10<00:00, 9384.27path/s]

transition AM=0: simulation returned; terminal storage=10.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=169
transition AM=0: payoff begin T=0.049315068493150684, contracts=164
transition AM=0: payoff begin T=0.052054794520547946, contracts=161
transition AM=0: payoff begin T=0.0547945205479452, contracts=168
transition AM=0: payoff begin T=0.057534246575342465, contracts=158
transition AM=0: payoff begin T=0.06027397260273973, contracts=231
transition AM=0: payoff begin T=0.0684931506849315, contracts=148
transition AM=0: payoff begin T=0.07123287671232877, contracts=145
transition AM=0: payoff begin T=0.07397260273972603, contracts=99
transition AM=0: payoff begin T=0.07671232876712329, contracts=99
transition AM=0: payoff begin T=0.07945205479452055, contracts=247
transition AM=0: payoff begin T=0.08767123287671233, contracts=96
transition AM=0: payoff begin T=0.09041095890410959, contracts=272
transition AM=0: payoff begin T=0.09315068493150686, contracts=68
transition AM=0: payoff begin T=0.0958904109589041, contracts=68
transition AM=0: payoff begin T=0.09863013698630137, contracts=177
transition AM=0: payoff begin T=0.10684931506849316, contracts=68
transition AM=0: payoff begin T=0.1178082191780822, contracts=108
transition AM=0: payoff begin T=0.136986301369863, contracts=361
transition AM=0: payoff begin T=0.17534246575342466, contracts=407
transition AM=0: payoff begin T=0.2328767123287671, contracts=423
transition AM=0: payoff begin T=0.25205479452054796, contracts=535
transition AM=0: payoff begin T=0.3095890410958904, contracts=352
transition AM=0: payoff begin T=0.3424657534246575, contracts=331
transition AM=0: payoff begin T=0.3863013698630137, contracts=365
transition AM=0: payoff begin T=0.4246575342465753, contracts=311
transition AM=0: payoff begin T=0.5095890410958904, contracts=149
transition AM=0: payoff begin T=0.7616438356164383, contracts=158
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3164

Future-date MC AM=1: 100%|██████████| 100000/100000 [00:10<00:00, 9421.30path/s]

transition AM=1: simulation returned; terminal storage=4.6 MiB
transition AM=1: payoff begin T=0.06027397260273973, contracts=235
transition AM=1: payoff begin T=0.136986301369863, contracts=370
transition AM=1: payoff begin T=0.2328767123287671, contracts=429
transition AM=1: payoff begin T=0.3095890410958904, contracts=447
transition AM=1: payoff begin T=0.3863013698630137, contracts=366
transition AM=1: payoff begin T=0.4821917808219178, contracts=360
transition AM=1: payoff begin T=0.5589041095890411, contracts=152
transition AM=1: payoff begin T=0.6356164383561644, contracts=156
transition AM=1: payoff begin T=0.7315068493150685, contracts=159
transition AM=1: payoff begin T=0.8082191780821918, contracts=158
transition AM=1: payoff begin T=0.9041095890410958, contracts=161
transition AM=1: payoff begin T=0.9808219178082191, contracts=171
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

PRIMARY FROZEN CONFIRMATION COMPLETE
{'otm_n': 57622, 'pooled_otm_pricing_RMSE': 3.2677472076291783, 'pooled_otm_NLV_hedge_RMSE': 1.901649744744149, 'pooled_otm_market_delta_hedge_RMSE': 1.3212814668259056, 'weighted_otm_pricing_MAE': 2.5472626566729506}

## 2. Primary untouched-test result

In [4]:
primary = sp.RUN_ROOT / "frozen_test_capped15_endpoint"
display(pd.read_csv(primary / "pooled_summary.csv"))
display(pd.read_csv(primary / "unseen_summary.csv"))

,variant,otm_n,pooled_otm_pricing_RMSE,pooled_otm_NLV_hedge_RMSE,pooled_otm_market_delta_hedge_RMSE,weighted_otm_pricing_MAE
0,frozen_test_capped15_endpoint,57622,3.267747,1.90165,1.321281,2.547263

,date,next_date,full_n,full_pricing_RMSE,full_pricing_MAE,full_pricing_Rel_MAE_pct,full_pricing_inside_bid_ask,full_NLV_hedge_RMSE,full_NLV_hedge_MAE,full_NLV_hedge_bias,...,otm_pricing_Rel_MAE_pct,otm_pricing_inside_bid_ask,otm_NLV_hedge_RMSE,otm_NLV_hedge_MAE,otm_NLV_hedge_bias,otm_market_delta_hedge_RMSE,otm_market_delta_hedge_MAE,otm_market_delta_hedge_bias,otm_NLV_minus_market_delta_RMSE,otm_delta_correlation
0,2024-03-08,2024-03-11,9350,6.651689,5.244914,5.085737,0.070588,2.474795,1.949630,-1.511464,...,8.025629,0.055397,1.201294,0.847895,-0.646012,1.323909,1.009280,-0.935654,0.055532,0.996961
1,2024-03-11,2024-03-12,9014,9.790324,7.752355,7.074710,0.025738,3.020835,2.763269,-2.719904,...,12.226235,0.042857,3.437819,3.208108,-3.208108,0.525617,0.388304,-0.201071,0.057770,0.996683
2,2024-03-12,2024-03-13,9001,7.253985,5.770221,4.396819,0.048328,1.257737,1.030494,-0.879322,...,6.188780,0.045397,1.141324,0.917889,-0.909276,1.518453,1.378353,-1.378347,0.051834,0.996920
3,2024-03-13,2024-03-14,8781,5.797954,4.522632,4.599025,0.103405,2.908011,2.604300,0.218515,...,7.626990,0.058484,2.265276,2.009310,1.540507,1.633431,1.498804,0.841765,0.052453,0.997046
4,2024-03-14,2024-03-15,9363,3.697469,2.926120,4.129225,0.310584,2.047921,1.742414,1.430131,...,7.472696,0.048331,1.829788,1.576973,1.546592,0.669306,0.532054,-0.243718,0.057803,0.997235
5,2024-03-15,2024-03-18,9178,6.412237,4.955359,5.262056,0.082916,2.280938,2.143032,-2.131471,...,8.773566,0.070260,2.266355,2.169959,-2.169959,0.574983,0.444559,-0.370135,0.059712,0.997275
6,2024-03-18,2024-03-19,9454,8.712558,6.754864,5.307438,0.033425,2.722517,2.215366,-1.342203,...,7.769374,0.068457,2.712675,2.304301,-2.304181,1.217099,0.965505,-0.746558,0.058009,0.997205
7,2024-03-19,2024-03-20,8781,7.243538,5.863554,7.538713,0.089398,4.868955,3.969643,-3.397891,...,13.756388,0.036391,2.117756,1.839738,-1.806216,1.621243,1.404857,0.466957,0.054038,0.996796
8,2024-03-20,2024-03-21,8904,8.209722,6.595259,6.197063,0.027965,2.432036,2.064862,0.166016,...,9.845190,0.028372,1.522764,1.326812,-0.984319,1.073490,0.773970,-0.149355,0.053971,0.996844
9,2024-03-21,2024-03-22,9601,7.923974,6.126389,4.095208,0.078429,1.225765,0.976400,-0.293397,...,4.675347,0.166190,0.913125,0.695609,-0.673292,1.153568,1.008765,-1.006807,0.050658,0.996931
10,2024-03-22,2024-03-25,9708,5.425335,4.143950,3.677307,0.088690,4.084496,3.315986,-2.038149,...,5.308537,0.110603,1.829632,1.322501,-0.539341,1.963240,1.433072,-1.266816,0.051747,0.996565
11,2024-03-25,2024-03-26,9512,6.406266,5.271128,4.916859,0.048991,2.003036,1.607697,-0.184764,...,7.069805,0.057714,1.158976,0.843687,-0.830674,1.855083,1.529094,-1.528996,0.053364,0.996711
12,2024-03-26,2024-03-27,9119,8.613114,6.973896,8.226517,0.087400,3.306556,2.794030,-2.365769,...,14.782591,0.075149,1.779529,1.617587,-1.499336,1.427152,1.316710,0.610439,0.053222,0.996001
13,2024-03-27,2024-03-28,9202,8.453960,6.804069,6.557450,0.021734,2.068993,1.566928,0.911800,...,10.104442,0.038489,0.619212,0.421537,0.042357,0.741051,0.572245,0.319141,0.052722,0.996336

## 3. 400k-path evaluation-only robustness check

This reuses the exact same trained checkpoints. There is **no retraining and no reopening of model selection**.

In [5]:
src = sp.RUN_ROOT / "frozen_test_capped15_endpoint"
if not (src / "unseen_summary.csv").exists():
    raise FileNotFoundError("Run the primary 100k frozen confirmation first.")

out400 = sp.RUN_ROOT / "frozen_test_capped15_endpoint_eval400k"
out400.mkdir(parents=True, exist_ok=True)

trading_dates = [pd.Timestamp(x) for x in ns["trading_dates"]]
start = trading_dates.index(pd.Timestamp("2024-03-08"))
training_dates = trading_dates[start:-1]
target_dates = trading_dates[start+1:]
assert len(training_dates) == 14 and len(target_dates) == 14

partial400 = out400 / "unseen_summary_400k_partial.csv"
summaries400 = []

transitions400 = list(zip(training_dates, target_dates))
outer400 = tqdm(
    transitions400,
    total=len(transitions400),
    desc="400k robustness eval",
    unit="transition",
    dynamic_ncols=True,
    mininterval=0.5,
    leave=True,
)

for index, (date, target) in enumerate(outer400, start=1):
    outer400.set_description(f"400k {date:%m-%d} → {target:%m-%d}")
    outer400.set_postfix_str("checkpoint/result")

    old = existing_row(partial400, date)
    if old is not None:
        outer400.set_postfix_str("reuse 400k result")
        summaries400.append(old)
        tqdm.write(f"[reuse 400k] {date.date()} → {target.date()}")
        continue

    cp = src / f"{date:%Y%m%d}_checkpoint.pt"
    model = load_model(cp)

    cfg = sp.SearchConfig(
        name="frozen_test_capped15_endpoint_eval400k",
        eval_paths=400000,
        seed_offset=0,
    )

    outer400.set_postfix_str("400k antithetic eval")
    tqdm.write(f"\nEVAL 400k {date.date()} → {target.date()}")
    s = sp.evaluate_one_transition(ns, model, date, target, cfg, out400, index)

    summaries400.append(s)
    pd.DataFrame(summaries400).to_csv(partial400, index=False)

    del model
    gc.collect()

outer400.close()

eval400_summary = pd.DataFrame(summaries400)
eval400_summary.to_csv(out400 / "unseen_summary_400k.csv", index=False)

eval400_pooled = pooled(eval400_summary)
pd.DataFrame([{
    "variant": "frozen_test_capped15_endpoint_eval400k",
    **eval400_pooled,
}]).to_csv(out400 / "pooled_summary_400k.csv", index=False)

print("\n400K ROBUSTNESS EVALUATION COMPLETE")
print(eval400_pooled)

400k robustness eval:   0%|          | 0/14 [00:00<?, ?transition/s]

EVAL 400k 2024-03-08 → 2024-03-11

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9568.91path/s]

transition: begin
transition AM=0: simulation begin, rows=6554

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:39<00:00, 10101.05path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=191
transition AM=0: payoff begin T=0.043835616438356165, contracts=191
transition AM=0: payoff begin T=0.04657534246575343, contracts=248
transition AM=0: payoff begin T=0.057534246575342465, contracts=188
transition AM=0: payoff begin T=0.06027397260273973, contracts=173
transition AM=0: payoff begin T=0.06301369863013699, contracts=175
transition AM=0: payoff begin T=0.06575342465753424, contracts=152
transition AM=0: payoff begin T=0.0684931506849315, contracts=249
transition AM=0: payoff begin T=0.07671232876712329, contracts=115
transition AM=0: payoff begin T=0.07945205479452055, contracts=112
transition AM=0: payoff begin T=0.0821917808219178, contracts=107
transition AM=0: payoff begin T=0.08493150684931507, contracts=99
transition AM=0: payoff begin T=0.08767123287671233, contracts=264
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10684931506849316, contracts=349
transition AM=0: payoff begin T=0.12602739726027398, contracts=179
transition AM=0: payoff begin T=0.136986301369863, contracts=384
transition AM=0: payoff begin T=0.14520547945205478, contracts=118
transition AM=0: payoff begin T=0.18356164383561643, contracts=401
transition AM=0: payoff begin T=0.2219178082191781, contracts=475
transition AM=0: payoff begin T=0.27945205479452057, contracts=350
transition AM=0: payoff begin T=0.29863013698630136, contracts=568
transition AM=0: payoff begin T=0.3561643835616438, contracts=370
transition AM=0: payoff begin T=0.38904109589041097, contracts=323
transition AM=0: payoff begin T=0.4712328767123288, contracts=298
transition AM=0: payoff begin T=0.5561643835616439, contracts=153
transition AM=0: payoff begin T=0.8082191780821918, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2796

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10459.43path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.10684931506849316, contracts=348
transition AM=1: payoff begin T=0.18356164383561643, contracts=415
transition AM=1: payoff begin T=0.27945205479452057, contracts=459
transition AM=1: payoff begin T=0.3561643835616438, contracts=370
transition AM=1: payoff begin T=0.4328767123287671, contracts=359
transition AM=1: payoff begin T=0.5287671232876713, contracts=149
transition AM=1: payoff begin T=0.6054794520547945, contracts=121
transition AM=1: payoff begin T=0.6821917808219178, contracts=123
transition AM=1: payoff begin T=0.7780821917808219, contracts=141
transition AM=1: payoff begin T=0.8547945205479452, contracts=145
transition AM=1: payoff begin T=0.9506849315068493, contracts=166
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-11 → 2024-03-12

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9579.40path/s]

transition: begin
transition AM=0: simulation begin, rows=6317

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10262.19path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=176
transition AM=0: payoff begin T=0.043835616438356165, contracts=221
transition AM=0: payoff begin T=0.0547945205479452, contracts=176
transition AM=0: payoff begin T=0.057534246575342465, contracts=165
transition AM=0: payoff begin T=0.06027397260273973, contracts=178
transition AM=0: payoff begin T=0.06301369863013699, contracts=155
transition AM=0: payoff begin T=0.06575342465753424, contracts=231
transition AM=0: payoff begin T=0.07397260273972603, contracts=111
transition AM=0: payoff begin T=0.07671232876712329, contracts=108
transition AM=0: payoff begin T=0.07945205479452055, contracts=105
transition AM=0: payoff begin T=0.0821917808219178, contracts=104
transition AM=0: payoff begin T=0.08493150684931507, contracts=246
transition AM=0: payoff begin T=0.09315068493150686, contracts=93
transition AM=0: payoff begin T=0.0958904109589041, contracts=64
transition AM=0: payoff begin T=0.09863013698630137, contracts=67
transition AM=0: payoff begin T=0.10410958904109589, contracts=320
transition AM=0: payoff begin T=0.1232876712328767, contracts=269
transition AM=0: payoff begin T=0.13424657534246576, contracts=359
transition AM=0: payoff begin T=0.14246575342465753, contracts=173
transition AM=0: payoff begin T=0.18082191780821918, contracts=381
transition AM=0: payoff begin T=0.2191780821917808, contracts=456
transition AM=0: payoff begin T=0.27671232876712326, contracts=339
transition AM=0: payoff begin T=0.2958904109589041, contracts=544
transition AM=0: payoff begin T=0.35342465753424657, contracts=358
transition AM=0: payoff begin T=0.3863013698630137, contracts=320
transition AM=0: payoff begin T=0.4684931506849315, contracts=296
transition AM=0: payoff begin T=0.5534246575342465, contracts=149
transition AM=0: payoff begin T=0.8054794520547945, contracts=153
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2697

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10502.62path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.10410958904109589, contracts=321
transition AM=1: payoff begin T=0.18082191780821918, contracts=395
transition AM=1: payoff begin T=0.27671232876712326, contracts=443
transition AM=1: payoff begin T=0.35342465753424657, contracts=358
transition AM=1: payoff begin T=0.4301369863013699, contracts=354
transition AM=1: payoff begin T=0.5260273972602739, contracts=145
transition AM=1: payoff begin T=0.6027397260273972, contracts=117
transition AM=1: payoff begin T=0.6794520547945205, contracts=121
transition AM=1: payoff begin T=0.7753424657534247, contracts=138
transition AM=1: payoff begin T=0.852054794520548, contracts=143
transition AM=1: payoff begin T=0.947945205479452, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-12 → 2024-03-13

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9684.68path/s]

transition: begin
transition AM=0: simulation begin, rows=6281

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:39<00:00, 10239.56path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=222
transition AM=0: payoff begin T=0.052054794520547946, contracts=178
transition AM=0: payoff begin T=0.0547945205479452, contracts=165
transition AM=0: payoff begin T=0.057534246575342465, contracts=178
transition AM=0: payoff begin T=0.06027397260273973, contracts=158
transition AM=0: payoff begin T=0.06301369863013699, contracts=233
transition AM=0: payoff begin T=0.07123287671232877, contracts=148
transition AM=0: payoff begin T=0.07397260273972603, contracts=108
transition AM=0: payoff begin T=0.07671232876712329, contracts=105
transition AM=0: payoff begin T=0.07945205479452055, contracts=104
transition AM=0: payoff begin T=0.0821917808219178, contracts=249
transition AM=0: payoff begin T=0.09041095890410959, contracts=97
transition AM=0: payoff begin T=0.09315068493150686, contracts=64
transition AM=0: payoff begin T=0.0958904109589041, contracts=67
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10136986301369863, contracts=323
transition AM=0: payoff begin T=0.12054794520547946, contracts=271
transition AM=0: payoff begin T=0.13150684931506848, contracts=363
transition AM=0: payoff begin T=0.13972602739726028, contracts=175
transition AM=0: payoff begin T=0.1780821917808219, contracts=383
transition AM=0: payoff begin T=0.21643835616438356, contracts=459
transition AM=0: payoff begin T=0.273972602739726, contracts=337
transition AM=0: payoff begin T=0.29315068493150687, contracts=545
transition AM=0: payoff begin T=0.3506849315068493, contracts=359
transition AM=0: payoff begin T=0.3835616438356164, contracts=321
transition AM=0: payoff begin T=0.4657534246575342, contracts=297
transition AM=0: payoff begin T=0.5506849315068493, contracts=150
transition AM=0: payoff begin T=0.8027397260273973, contracts=154
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2720

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10339.00path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.10136986301369863, contracts=325
transition AM=1: payoff begin T=0.1780821917808219, contracts=396
transition AM=1: payoff begin T=0.273972602739726, contracts=444
transition AM=1: payoff begin T=0.3506849315068493, contracts=359
transition AM=1: payoff begin T=0.4273972602739726, contracts=354
transition AM=1: payoff begin T=0.5232876712328767, contracts=145
transition AM=1: payoff begin T=0.6, contracts=117
transition AM=1: payoff begin T=0.6767123287671233, contracts=121
transition AM=1: payoff begin T=0.7726027397260274, contracts=154
transition AM=1: payoff begin T=0.8493150684931506, contracts=143
transition AM=1: payoff begin T=0.9452054794520548, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-13 → 2024-03-14

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9750.68path/s]

transition: begin
transition AM=0: simulation begin, rows=6100

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10453.58path/s]

transition AM=0: simulation returned; terminal storage=41.2 MiB
transition AM=0: payoff begin T=0.049315068493150684, contracts=177
transition AM=0: payoff begin T=0.052054794520547946, contracts=177
transition AM=0: payoff begin T=0.0547945205479452, contracts=179
transition AM=0: payoff begin T=0.057534246575342465, contracts=160
transition AM=0: payoff begin T=0.06027397260273973, contracts=218
transition AM=0: payoff begin T=0.0684931506849315, contracts=174
transition AM=0: payoff begin T=0.07123287671232877, contracts=151
transition AM=0: payoff begin T=0.07397260273972603, contracts=104
transition AM=0: payoff begin T=0.07671232876712329, contracts=103
transition AM=0: payoff begin T=0.07945205479452055, contracts=237
transition AM=0: payoff begin T=0.08767123287671233, contracts=106
transition AM=0: payoff begin T=0.09041095890410959, contracts=94
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=65
transition AM=0: payoff begin T=0.09863013698630137, contracts=299
transition AM=0: payoff begin T=0.1178082191780822, contracts=281
transition AM=0: payoff begin T=0.12876712328767123, contracts=345
transition AM=0: payoff begin T=0.136986301369863, contracts=184
transition AM=0: payoff begin T=0.17534246575342466, contracts=372
transition AM=0: payoff begin T=0.2136986301369863, contracts=448
transition AM=0: payoff begin T=0.27123287671232876, contracts=320
transition AM=0: payoff begin T=0.29041095890410956, contracts=541
transition AM=0: payoff begin T=0.34794520547945207, contracts=359
transition AM=0: payoff begin T=0.38082191780821917, contracts=326
transition AM=0: payoff begin T=0.46301369863013697, contracts=305
transition AM=0: payoff begin T=0.547945205479452, contracts=153
transition AM=0: payoff begin T=0.8, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2681

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:37<00:00, 10559.27path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.09863013698630137, contracts=303
transition AM=1: payoff begin T=0.17534246575342466, contracts=384
transition AM=1: payoff begin T=0.27123287671232876, contracts=428
transition AM=1: payoff begin T=0.34794520547945207, contracts=357
transition AM=1: payoff begin T=0.4246575342465753, contracts=358
transition AM=1: payoff begin T=0.5205479452054794, contracts=148
transition AM=1: payoff begin T=0.5972602739726027, contracts=119
transition AM=1: payoff begin T=0.673972602739726, contracts=121
transition AM=1: payoff begin T=0.7698630136986301, contracts=156
transition AM=1: payoff begin T=0.8465753424657534, contracts=143
transition AM=1: payoff begin T=0.9424657534246575, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-14 → 2024-03-15

Same-day MC: 100%|██████████| 400000/400000 [00:40<00:00, 9791.96path/s]

transition: begin
transition AM=0: simulation begin, rows=6659

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:39<00:00, 10248.29path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.04657534246575343, contracts=175
transition AM=0: payoff begin T=0.049315068493150684, contracts=177
transition AM=0: payoff begin T=0.052054794520547946, contracts=179
transition AM=0: payoff begin T=0.0547945205479452, contracts=160
transition AM=0: payoff begin T=0.057534246575342465, contracts=214
transition AM=0: payoff begin T=0.06575342465753424, contracts=175
transition AM=0: payoff begin T=0.0684931506849315, contracts=152
transition AM=0: payoff begin T=0.07123287671232877, contracts=149
transition AM=0: payoff begin T=0.07397260273972603, contracts=103
transition AM=0: payoff begin T=0.07671232876712329, contracts=232
transition AM=0: payoff begin T=0.08493150684931507, contracts=106
transition AM=0: payoff begin T=0.08767123287671233, contracts=98
transition AM=0: payoff begin T=0.09041095890410959, contracts=96
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=303
transition AM=0: payoff begin T=0.10410958904109589, contracts=98
transition AM=0: payoff begin T=0.11506849315068493, contracts=281
transition AM=0: payoff begin T=0.12602739726027398, contracts=346
transition AM=0: payoff begin T=0.13424657534246576, contracts=184
transition AM=0: payoff begin T=0.1726027397260274, contracts=376
transition AM=0: payoff begin T=0.21095890410958903, contracts=448
transition AM=0: payoff begin T=0.2684931506849315, contracts=324
transition AM=0: payoff begin T=0.2876712328767123, contracts=549
transition AM=0: payoff begin T=0.3452054794520548, contracts=365
transition AM=0: payoff begin T=0.3780821917808219, contracts=329
transition AM=0: payoff begin T=0.42191780821917807, contracts=358
transition AM=0: payoff begin T=0.4602739726027397, contracts=304
transition AM=0: payoff begin T=0.5452054794520548, contracts=154
transition AM=0: payoff begin T=0.7972602739726027, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2704

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:37<00:00, 10564.08path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.0958904109589041, contracts=302
transition AM=1: payoff begin T=0.1726027397260274, contracts=388
transition AM=1: payoff begin T=0.2684931506849315, contracts=432
transition AM=1: payoff begin T=0.3452054794520548, contracts=362
transition AM=1: payoff begin T=0.42191780821917807, contracts=358
transition AM=1: payoff begin T=0.5178082191780822, contracts=151
transition AM=1: payoff begin T=0.5945205479452055, contracts=119
transition AM=1: payoff begin T=0.6712328767123288, contracts=123
transition AM=1: payoff begin T=0.7671232876712328, contracts=160
transition AM=1: payoff begin T=0.8438356164383561, contracts=145
transition AM=1: payoff begin T=0.9397260273972603, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-15 → 2024-03-18

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9690.54path/s]

transition: begin
transition AM=0: simulation begin, rows=6486

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10330.10path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=167
transition AM=0: payoff begin T=0.043835616438356165, contracts=172
transition AM=0: payoff begin T=0.04657534246575343, contracts=163
transition AM=0: payoff begin T=0.049315068493150684, contracts=203
transition AM=0: payoff begin T=0.057534246575342465, contracts=172
transition AM=0: payoff begin T=0.06027397260273973, contracts=153
transition AM=0: payoff begin T=0.06301369863013699, contracts=148
transition AM=0: payoff begin T=0.06575342465753424, contracts=143
transition AM=0: payoff begin T=0.0684931506849315, contracts=225
transition AM=0: payoff begin T=0.07671232876712329, contracts=105
transition AM=0: payoff begin T=0.07945205479452055, contracts=97
transition AM=0: payoff begin T=0.0821917808219178, contracts=95
transition AM=0: payoff begin T=0.08493150684931507, contracts=93
transition AM=0: payoff begin T=0.08767123287671233, contracts=292
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=61
transition AM=0: payoff begin T=0.10684931506849316, contracts=275
transition AM=0: payoff begin T=0.1178082191780822, contracts=332
transition AM=0: payoff begin T=0.12602739726027398, contracts=183
transition AM=0: payoff begin T=0.1643835616438356, contracts=370
transition AM=0: payoff begin T=0.20273972602739726, contracts=443
transition AM=0: payoff begin T=0.2602739726027397, contracts=330
transition AM=0: payoff begin T=0.27945205479452057, contracts=544
transition AM=0: payoff begin T=0.336986301369863, contracts=365
transition AM=0: payoff begin T=0.3698630136986301, contracts=328
transition AM=0: payoff begin T=0.4136986301369863, contracts=312
transition AM=0: payoff begin T=0.4520547945205479, contracts=304
transition AM=0: payoff begin T=0.536986301369863, contracts=155
transition AM=0: payoff begin T=0.7890410958904109, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2692

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10502.42path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.08767123287671233, contracts=291
transition AM=1: payoff begin T=0.1643835616438356, contracts=381
transition AM=1: payoff begin T=0.2602739726027397, contracts=437
transition AM=1: payoff begin T=0.336986301369863, contracts=363
transition AM=1: payoff begin T=0.4136986301369863, contracts=358
transition AM=1: payoff begin T=0.5095890410958904, contracts=151
transition AM=1: payoff begin T=0.5863013698630137, contracts=119
transition AM=1: payoff begin T=0.663013698630137, contracts=123
transition AM=1: payoff begin T=0.7589041095890411, contracts=160
transition AM=1: payoff begin T=0.8356164383561644, contracts=145
transition AM=1: payoff begin T=0.9315068493150684, contracts=164
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-18 → 2024-03-19

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9713.67path/s]

transition: begin
transition AM=0: simulation begin, rows=6514

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:42<00:00, 9481.08path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=166
transition AM=0: payoff begin T=0.043835616438356165, contracts=163
transition AM=0: payoff begin T=0.04657534246575343, contracts=192
transition AM=0: payoff begin T=0.0547945205479452, contracts=183
transition AM=0: payoff begin T=0.057534246575342465, contracts=159
transition AM=0: payoff begin T=0.06027397260273973, contracts=174
transition AM=0: payoff begin T=0.06301369863013699, contracts=155
transition AM=0: payoff begin T=0.06575342465753424, contracts=220
transition AM=0: payoff begin T=0.07397260273972603, contracts=103
transition AM=0: payoff begin T=0.07671232876712329, contracts=103
transition AM=0: payoff begin T=0.07945205479452055, contracts=102
transition AM=0: payoff begin T=0.0821917808219178, contracts=100
transition AM=0: payoff begin T=0.08493150684931507, contracts=282
transition AM=0: payoff begin T=0.09315068493150686, contracts=96
transition AM=0: payoff begin T=0.0958904109589041, contracts=61
transition AM=0: payoff begin T=0.09863013698630137, contracts=61
transition AM=0: payoff begin T=0.10410958904109589, contracts=273
transition AM=0: payoff begin T=0.11506849315068493, contracts=324
transition AM=0: payoff begin T=0.1232876712328767, contracts=183
transition AM=0: payoff begin T=0.16164383561643836, contracts=363
transition AM=0: payoff begin T=0.2, contracts=440
transition AM=0: payoff begin T=0.25753424657534246, contracts=422
transition AM=0: payoff begin T=0.27671232876712326, contracts=584
transition AM=0: payoff begin T=0.33424657534246577, contracts=358
transition AM=0: payoff begin T=0.36712328767123287, contracts=325
transition AM=0: payoff begin T=0.410958904109589, contracts=311
transition AM=0: payoff begin T=0.44931506849315067, contracts=302
transition AM=0: payoff begin T=0.5342465753424658, contracts=152
transition AM=0: payoff begin T=0.7863013698630137, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2940

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10515.58path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.08493150684931507, contracts=281
transition AM=1: payoff begin T=0.16164383561643836, contracts=373
transition AM=1: payoff begin T=0.25753424657534246, contracts=432
transition AM=1: payoff begin T=0.33424657534246577, contracts=430
transition AM=1: payoff begin T=0.410958904109589, contracts=355
transition AM=1: payoff begin T=0.5068493150684932, contracts=334
transition AM=1: payoff begin T=0.5835616438356165, contracts=148
transition AM=1: payoff begin T=0.6602739726027397, contracts=125
transition AM=1: payoff begin T=0.7561643835616438, contracts=157
transition AM=1: payoff begin T=0.8328767123287671, contracts=143
transition AM=1: payoff begin T=0.9287671232876712, contracts=162
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-19 → 2024-03-20

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9737.42path/s]

transition: begin
transition AM=0: simulation begin, rows=5989

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10352.87path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=124
transition AM=0: payoff begin T=0.043835616438356165, contracts=150
transition AM=0: payoff begin T=0.052054794520547946, contracts=145
transition AM=0: payoff begin T=0.0547945205479452, contracts=134
transition AM=0: payoff begin T=0.057534246575342465, contracts=148
transition AM=0: payoff begin T=0.06027397260273973, contracts=144
transition AM=0: payoff begin T=0.06301369863013699, contracts=192
transition AM=0: payoff begin T=0.07123287671232877, contracts=138
transition AM=0: payoff begin T=0.07397260273972603, contracts=98
transition AM=0: payoff begin T=0.07671232876712329, contracts=97
transition AM=0: payoff begin T=0.07945205479452055, contracts=95
transition AM=0: payoff begin T=0.0821917808219178, contracts=240
transition AM=0: payoff begin T=0.09041095890410959, contracts=91
transition AM=0: payoff begin T=0.09315068493150686, contracts=59
transition AM=0: payoff begin T=0.0958904109589041, contracts=60
transition AM=0: payoff begin T=0.09863013698630137, contracts=62
transition AM=0: payoff begin T=0.10136986301369863, contracts=247
transition AM=0: payoff begin T=0.11232876712328767, contracts=282
transition AM=0: payoff begin T=0.12054794520547946, contracts=174
transition AM=0: payoff begin T=0.1589041095890411, contracts=334
transition AM=0: payoff begin T=0.19726027397260273, contracts=413
transition AM=0: payoff begin T=0.2547945205479452, contracts=396
transition AM=0: payoff begin T=0.273972602739726, contracts=545
transition AM=0: payoff begin T=0.3315068493150685, contracts=345
transition AM=0: payoff begin T=0.3643835616438356, contracts=320
transition AM=0: payoff begin T=0.40821917808219177, contracts=351
transition AM=0: payoff begin T=0.4465753424657534, contracts=301
transition AM=0: payoff begin T=0.5315068493150685, contracts=148
transition AM=0: payoff begin T=0.7835616438356164, contracts=156
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2792

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:37<00:00, 10647.88path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.0821917808219178, contracts=235
transition AM=1: payoff begin T=0.1589041095890411, contracts=339
transition AM=1: payoff begin T=0.2547945205479452, contracts=402
transition AM=1: payoff begin T=0.3315068493150685, contracts=415
transition AM=1: payoff begin T=0.40821917808219177, contracts=351
transition AM=1: payoff begin T=0.5041095890410959, contracts=330
transition AM=1: payoff begin T=0.5808219178082191, contracts=145
transition AM=1: payoff begin T=0.6575342465753424, contracts=121
transition AM=1: payoff begin T=0.7534246575342466, contracts=155
transition AM=1: payoff begin T=0.8301369863013699, contracts=139
transition AM=1: payoff begin T=0.9260273972602739, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-20 → 2024-03-21

Same-day MC: 100%|██████████| 400000/400000 [00:40<00:00, 9805.51path/s]

transition: begin
transition AM=0: simulation begin, rows=6103

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10376.16path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=147
transition AM=0: payoff begin T=0.049315068493150684, contracts=138
transition AM=0: payoff begin T=0.052054794520547946, contracts=143
transition AM=0: payoff begin T=0.0547945205479452, contracts=146
transition AM=0: payoff begin T=0.057534246575342465, contracts=151
transition AM=0: payoff begin T=0.06027397260273973, contracts=193
transition AM=0: payoff begin T=0.0684931506849315, contracts=148
transition AM=0: payoff begin T=0.07123287671232877, contracts=142
transition AM=0: payoff begin T=0.07397260273972603, contracts=100
transition AM=0: payoff begin T=0.07671232876712329, contracts=101
transition AM=0: payoff begin T=0.07945205479452055, contracts=242
transition AM=0: payoff begin T=0.08767123287671233, contracts=95
transition AM=0: payoff begin T=0.09041095890410959, contracts=91
transition AM=0: payoff begin T=0.09315068493150686, contracts=61
transition AM=0: payoff begin T=0.0958904109589041, contracts=62
transition AM=0: payoff begin T=0.09863013698630137, contracts=249
transition AM=0: payoff begin T=0.1095890410958904, contracts=284
transition AM=0: payoff begin T=0.1178082191780822, contracts=173
transition AM=0: payoff begin T=0.136986301369863, contracts=108
transition AM=0: payoff begin T=0.15616438356164383, contracts=335
transition AM=0: payoff begin T=0.19452054794520549, contracts=420
transition AM=0: payoff begin T=0.25205479452054796, contracts=397
transition AM=0: payoff begin T=0.27123287671232876, contracts=553
transition AM=0: payoff begin T=0.3287671232876712, contracts=345
transition AM=0: payoff begin T=0.36164383561643837, contracts=321
transition AM=0: payoff begin T=0.4054794520547945, contracts=353
transition AM=0: payoff begin T=0.4438356164383562, contracts=301
transition AM=0: payoff begin T=0.5287671232876713, contracts=149
transition AM=0: payoff begin T=0.7808219178082192, contracts=155
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2801

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:37<00:00, 10643.37path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.07945205479452055, contracts=237
transition AM=1: payoff begin T=0.15616438356164383, contracts=340
transition AM=1: payoff begin T=0.25205479452054796, contracts=403
transition AM=1: payoff begin T=0.3287671232876712, contracts=416
transition AM=1: payoff begin T=0.4054794520547945, contracts=353
transition AM=1: payoff begin T=0.5013698630136987, contracts=331
transition AM=1: payoff begin T=0.5780821917808219, contracts=146
transition AM=1: payoff begin T=0.6547945205479452, contracts=121
transition AM=1: payoff begin T=0.7506849315068493, contracts=155
transition AM=1: payoff begin T=0.8273972602739726, contracts=139
transition AM=1: payoff begin T=0.9232876712328767, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-21 → 2024-03-22

Same-day MC: 100%|██████████| 400000/400000 [00:40<00:00, 9850.05path/s]

transition: begin
transition AM=0: simulation begin, rows=6650

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10331.33path/s]

transition AM=0: simulation returned; terminal storage=44.3 MiB
transition AM=0: payoff begin T=0.04657534246575343, contracts=170
transition AM=0: payoff begin T=0.049315068493150684, contracts=167
transition AM=0: payoff begin T=0.052054794520547946, contracts=187
transition AM=0: payoff begin T=0.0547945205479452, contracts=171
transition AM=0: payoff begin T=0.057534246575342465, contracts=217
transition AM=0: payoff begin T=0.06575342465753424, contracts=179
transition AM=0: payoff begin T=0.0684931506849315, contracts=161
transition AM=0: payoff begin T=0.07123287671232877, contracts=173
transition AM=0: payoff begin T=0.07397260273972603, contracts=113
transition AM=0: payoff begin T=0.07671232876712329, contracts=277
transition AM=0: payoff begin T=0.08493150684931507, contracts=107
transition AM=0: payoff begin T=0.08767123287671233, contracts=102
transition AM=0: payoff begin T=0.09041095890410959, contracts=99
transition AM=0: payoff begin T=0.09315068493150686, contracts=65
transition AM=0: payoff begin T=0.0958904109589041, contracts=277
transition AM=0: payoff begin T=0.10410958904109589, contracts=100
transition AM=0: payoff begin T=0.10684931506849316, contracts=317
transition AM=0: payoff begin T=0.11506849315068493, contracts=185
transition AM=0: payoff begin T=0.13424657534246576, contracts=113
transition AM=0: payoff begin T=0.15342465753424658, contracts=367
transition AM=0: payoff begin T=0.1917808219178082, contracts=435
transition AM=0: payoff begin T=0.2493150684931507, contracts=420
transition AM=0: payoff begin T=0.2684931506849315, contracts=573
transition AM=0: payoff begin T=0.32602739726027397, contracts=357
transition AM=0: payoff begin T=0.3589041095890411, contracts=334
transition AM=0: payoff begin T=0.40273972602739727, contracts=365
transition AM=0: payoff begin T=0.4410958904109589, contracts=310
transition AM=0: payoff begin T=0.5260273972602739, contracts=151
transition AM=0: payoff begin T=0.7780821917808219, contracts=158
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=2951

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:37<00:00, 10567.85path/s]

transition AM=1: simulation returned; terminal storage=16.8 MiB
transition AM=1: payoff begin T=0.07671232876712329, contracts=275
transition AM=1: payoff begin T=0.15342465753424658, contracts=371
transition AM=1: payoff begin T=0.2493150684931507, contracts=427
transition AM=1: payoff begin T=0.32602739726027397, contracts=430
transition AM=1: payoff begin T=0.40273972602739727, contracts=364
transition AM=1: payoff begin T=0.4986301369863014, contracts=357
transition AM=1: payoff begin T=0.5753424657534246, contracts=152
transition AM=1: payoff begin T=0.6520547945205479, contracts=121
transition AM=1: payoff begin T=0.7479452054794521, contracts=155
transition AM=1: payoff begin T=0.8246575342465754, contracts=139
transition AM=1: payoff begin T=0.9205479452054794, contracts=160
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-22 → 2024-03-25

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9585.68path/s]

transition: begin
transition AM=0: simulation begin, rows=6483

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10515.82path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=158
transition AM=0: payoff begin T=0.043835616438356165, contracts=174
transition AM=0: payoff begin T=0.04657534246575343, contracts=180
transition AM=0: payoff begin T=0.049315068493150684, contracts=204
transition AM=0: payoff begin T=0.057534246575342465, contracts=180
transition AM=0: payoff begin T=0.06027397260273973, contracts=165
transition AM=0: payoff begin T=0.06301369863013699, contracts=177
transition AM=0: payoff begin T=0.06575342465753424, contracts=161
transition AM=0: payoff begin T=0.0684931506849315, contracts=257
transition AM=0: payoff begin T=0.07671232876712329, contracts=108
transition AM=0: payoff begin T=0.07945205479452055, contracts=104
transition AM=0: payoff begin T=0.0821917808219178, contracts=99
transition AM=0: payoff begin T=0.08493150684931507, contracts=96
transition AM=0: payoff begin T=0.08767123287671233, contracts=265
transition AM=0: payoff begin T=0.0958904109589041, contracts=97
transition AM=0: payoff begin T=0.09863013698630137, contracts=298
transition AM=0: payoff begin T=0.10684931506849316, contracts=185
transition AM=0: payoff begin T=0.12602739726027398, contracts=109
transition AM=0: payoff begin T=0.14520547945205478, contracts=375
transition AM=0: payoff begin T=0.18356164383561643, contracts=421
transition AM=0: payoff begin T=0.2410958904109589, contracts=431
transition AM=0: payoff begin T=0.2602739726027397, contracts=554
transition AM=0: payoff begin T=0.3178082191780822, contracts=358
transition AM=0: payoff begin T=0.3506849315068493, contracts=335
transition AM=0: payoff begin T=0.39452054794520547, contracts=369
transition AM=0: payoff begin T=0.4328767123287671, contracts=314
transition AM=0: payoff begin T=0.5178082191780822, contracts=152
transition AM=0: payoff begin T=0.7698630136986301, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3225

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10275.49path/s]

transition AM=1: simulation returned; terminal storage=18.3 MiB
transition AM=1: payoff begin T=0.0684931506849315, contracts=258
transition AM=1: payoff begin T=0.14520547945205478, contracts=384
transition AM=1: payoff begin T=0.2410958904109589, contracts=438
transition AM=1: payoff begin T=0.3178082191780822, contracts=452
transition AM=1: payoff begin T=0.39452054794520547, contracts=368
transition AM=1: payoff begin T=0.4904109589041096, contracts=361
transition AM=1: payoff begin T=0.5671232876712329, contracts=155
transition AM=1: payoff begin T=0.6438356164383562, contracts=156
transition AM=1: payoff begin T=0.7397260273972602, contracts=161
transition AM=1: payoff begin T=0.8164383561643835, contracts=158
transition AM=1: payoff begin T=0.9123287671232877, contracts=161
transition AM=1: payoff begin T=0.989041095890411, contracts=173
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-25 → 2024-03-26

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9703.44path/s]

transition: begin
transition AM=0: simulation begin, rows=6305

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10395.69path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=167
transition AM=0: payoff begin T=0.043835616438356165, contracts=175
transition AM=0: payoff begin T=0.04657534246575343, contracts=194
transition AM=0: payoff begin T=0.0547945205479452, contracts=174
transition AM=0: payoff begin T=0.057534246575342465, contracts=163
transition AM=0: payoff begin T=0.06027397260273973, contracts=173
transition AM=0: payoff begin T=0.06301369863013699, contracts=158
transition AM=0: payoff begin T=0.06575342465753424, contracts=244
transition AM=0: payoff begin T=0.07397260273972603, contracts=107
transition AM=0: payoff begin T=0.07671232876712329, contracts=104
transition AM=0: payoff begin T=0.07945205479452055, contracts=98
transition AM=0: payoff begin T=0.0821917808219178, contracts=96
transition AM=0: payoff begin T=0.08493150684931507, contracts=259
transition AM=0: payoff begin T=0.09315068493150686, contracts=96
transition AM=0: payoff begin T=0.0958904109589041, contracts=290
transition AM=0: payoff begin T=0.09863013698630137, contracts=71
transition AM=0: payoff begin T=0.10410958904109589, contracts=182
transition AM=0: payoff begin T=0.1232876712328767, contracts=108
transition AM=0: payoff begin T=0.14246575342465753, contracts=370
transition AM=0: payoff begin T=0.18082191780821918, contracts=414
transition AM=0: payoff begin T=0.23835616438356164, contracts=430
transition AM=0: payoff begin T=0.25753424657534246, contracts=549
transition AM=0: payoff begin T=0.3150684931506849, contracts=357
transition AM=0: payoff begin T=0.34794520547945207, contracts=334
transition AM=0: payoff begin T=0.3917808219178082, contracts=367
transition AM=0: payoff begin T=0.4301369863013699, contracts=314
transition AM=0: payoff begin T=0.5150684931506849, contracts=152
transition AM=0: payoff begin T=0.7671232876712328, contracts=159
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3207

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10265.23path/s]

transition AM=1: simulation returned; terminal storage=18.3 MiB
transition AM=1: payoff begin T=0.06575342465753424, contracts=246
transition AM=1: payoff begin T=0.14246575342465753, contracts=376
transition AM=1: payoff begin T=0.23835616438356164, contracts=433
transition AM=1: payoff begin T=0.3150684931506849, contracts=453
transition AM=1: payoff begin T=0.3917808219178082, contracts=367
transition AM=1: payoff begin T=0.4876712328767123, contracts=362
transition AM=1: payoff begin T=0.5643835616438356, contracts=156
transition AM=1: payoff begin T=0.6410958904109589, contracts=158
transition AM=1: payoff begin T=0.736986301369863, contracts=160
transition AM=1: payoff begin T=0.8136986301369863, contracts=160
transition AM=1: payoff begin T=0.9095890410958904, contracts=162
transition AM=1: payoff begin T=0.9863013698630136, contracts=174
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-26 → 2024-03-27

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9595.68path/s]

transition: begin
transition AM=0: simulation begin, rows=5984

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:38<00:00, 10457.92path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=153
transition AM=0: payoff begin T=0.043835616438356165, contracts=162
transition AM=0: payoff begin T=0.052054794520547946, contracts=160
transition AM=0: payoff begin T=0.0547945205479452, contracts=154
transition AM=0: payoff begin T=0.057534246575342465, contracts=164
transition AM=0: payoff begin T=0.06027397260273973, contracts=154
transition AM=0: payoff begin T=0.06301369863013699, contracts=221
transition AM=0: payoff begin T=0.07123287671232877, contracts=145
transition AM=0: payoff begin T=0.07397260273972603, contracts=101
transition AM=0: payoff begin T=0.07671232876712329, contracts=98
transition AM=0: payoff begin T=0.07945205479452055, contracts=97
transition AM=0: payoff begin T=0.0821917808219178, contracts=242
transition AM=0: payoff begin T=0.09041095890410959, contracts=95
transition AM=0: payoff begin T=0.09315068493150686, contracts=264
transition AM=0: payoff begin T=0.0958904109589041, contracts=68
transition AM=0: payoff begin T=0.09863013698630137, contracts=68
transition AM=0: payoff begin T=0.10136986301369863, contracts=174
transition AM=0: payoff begin T=0.12054794520547946, contracts=106
transition AM=0: payoff begin T=0.13972602739726028, contracts=354
transition AM=0: payoff begin T=0.1780821917808219, contracts=398
transition AM=0: payoff begin T=0.2356164383561644, contracts=421
transition AM=0: payoff begin T=0.2547945205479452, contracts=528
transition AM=0: payoff begin T=0.31232876712328766, contracts=349
transition AM=0: payoff begin T=0.3452054794520548, contracts=329
transition AM=0: payoff begin T=0.38904109589041097, contracts=362
transition AM=0: payoff begin T=0.4273972602739726, contracts=311
transition AM=0: payoff begin T=0.5123287671232877, contracts=149
transition AM=0: payoff begin T=0.7643835616438356, contracts=157
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3135

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:38<00:00, 10352.65path/s]

transition AM=1: simulation returned; terminal storage=18.3 MiB
transition AM=1: payoff begin T=0.06301369863013699, contracts=226
transition AM=1: payoff begin T=0.13972602739726028, contracts=360
transition AM=1: payoff begin T=0.2356164383561644, contracts=424
transition AM=1: payoff begin T=0.31232876712328766, contracts=445
transition AM=1: payoff begin T=0.38904109589041097, contracts=364
transition AM=1: payoff begin T=0.4849315068493151, contracts=359
transition AM=1: payoff begin T=0.5616438356164384, contracts=153
transition AM=1: payoff begin T=0.6383561643835617, contracts=156
transition AM=1: payoff begin T=0.7342465753424657, contracts=158
transition AM=1: payoff begin T=0.810958904109589, contracts=158
transition AM=1: payoff begin T=0.9068493150684932, contracts=160
transition AM=1: payoff begin T=0.9835616438356164, contracts=172
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

EVAL 400k 2024-03-27 → 2024-03-28

Same-day MC: 100%|██████████| 400000/400000 [00:41<00:00, 9570.99path/s]

transition: begin
transition AM=0: simulation begin, rows=6038

Future-date MC AM=0: 100%|██████████| 400000/400000 [00:37<00:00, 10558.00path/s]

transition AM=0: simulation returned; terminal storage=42.7 MiB
transition AM=0: payoff begin T=0.0410958904109589, contracts=169
transition AM=0: payoff begin T=0.049315068493150684, contracts=164
transition AM=0: payoff begin T=0.052054794520547946, contracts=161
transition AM=0: payoff begin T=0.0547945205479452, contracts=168
transition AM=0: payoff begin T=0.057534246575342465, contracts=158
transition AM=0: payoff begin T=0.06027397260273973, contracts=231
transition AM=0: payoff begin T=0.0684931506849315, contracts=148
transition AM=0: payoff begin T=0.07123287671232877, contracts=145
transition AM=0: payoff begin T=0.07397260273972603, contracts=99
transition AM=0: payoff begin T=0.07671232876712329, contracts=99
transition AM=0: payoff begin T=0.07945205479452055, contracts=247
transition AM=0: payoff begin T=0.08767123287671233, contracts=96
transition AM=0: payoff begin T=0.09041095890410959, contracts=272
transition AM=0: payoff begin T=0.09315068493150686, contracts=68
transition AM=0: payoff begin T=0.0958904109589041, contracts=68
transition AM=0: payoff begin T=0.09863013698630137, contracts=177
transition AM=0: payoff begin T=0.10684931506849316, contracts=68
transition AM=0: payoff begin T=0.1178082191780822, contracts=108
transition AM=0: payoff begin T=0.136986301369863, contracts=361
transition AM=0: payoff begin T=0.17534246575342466, contracts=407
transition AM=0: payoff begin T=0.2328767123287671, contracts=423
transition AM=0: payoff begin T=0.25205479452054796, contracts=535
transition AM=0: payoff begin T=0.3095890410958904, contracts=352
transition AM=0: payoff begin T=0.3424657534246575, contracts=331
transition AM=0: payoff begin T=0.3863013698630137, contracts=365
transition AM=0: payoff begin T=0.4246575342465753, contracts=311
transition AM=0: payoff begin T=0.5095890410958904, contracts=149
transition AM=0: payoff begin T=0.7616438356164383, contracts=158
transition AM=0: pricing complete
transition AM=1: simulation begin, rows=3164

Future-date MC AM=1: 100%|██████████| 400000/400000 [00:39<00:00, 10221.48path/s]

transition AM=1: simulation returned; terminal storage=18.3 MiB
transition AM=1: payoff begin T=0.06027397260273973, contracts=235
transition AM=1: payoff begin T=0.136986301369863, contracts=370
transition AM=1: payoff begin T=0.2328767123287671, contracts=429
transition AM=1: payoff begin T=0.3095890410958904, contracts=447
transition AM=1: payoff begin T=0.3863013698630137, contracts=366
transition AM=1: payoff begin T=0.4821917808219178, contracts=360
transition AM=1: payoff begin T=0.5589041095890411, contracts=152
transition AM=1: payoff begin T=0.6356164383561644, contracts=156
transition AM=1: payoff begin T=0.7315068493150685, contracts=159
transition AM=1: payoff begin T=0.8082191780821918, contracts=158
transition AM=1: payoff begin T=0.9041095890410958, contracts=161
transition AM=1: payoff begin T=0.9808219178082191, contracts=171
transition AM=1: pricing complete
transition: concatenate begin
transition: delta merge begin
transition: hedge calculations complete; OTM flags begin
transition: full summary begin
transition: OTM summary begin
transition: complete

400K ROBUSTNESS EVALUATION COMPLETE
{'otm_n': 57622, 'pooled_otm_pricing_RMSE': 3.2208396614039247, 'pooled_otm_NLV_hedge_RMSE': 1.900956212659932, 'pooled_otm_market_delta_hedge_RMSE': 1.3212814668259056, 'weighted_otm_pricing_MAE': 2.5252783523961857}

## 4. 400k robustness result

In [6]:
eval400 = sp.RUN_ROOT / "frozen_test_capped15_endpoint_eval400k"
display(pd.read_csv(eval400 / "pooled_summary_400k.csv"))
display(pd.read_csv(eval400 / "unseen_summary_400k.csv"))

,variant,otm_n,pooled_otm_pricing_RMSE,pooled_otm_NLV_hedge_RMSE,pooled_otm_market_delta_hedge_RMSE,weighted_otm_pricing_MAE
0,frozen_test_capped15_endpoint_eval400k,57622,3.22084,1.900956,1.321281,2.525278

,date,next_date,full_n,full_pricing_RMSE,full_pricing_MAE,full_pricing_Rel_MAE_pct,full_pricing_inside_bid_ask,full_NLV_hedge_RMSE,full_NLV_hedge_MAE,full_NLV_hedge_bias,...,otm_pricing_Rel_MAE_pct,otm_pricing_inside_bid_ask,otm_NLV_hedge_RMSE,otm_NLV_hedge_MAE,otm_NLV_hedge_bias,otm_market_delta_hedge_RMSE,otm_market_delta_hedge_MAE,otm_market_delta_hedge_bias,otm_NLV_minus_market_delta_RMSE,otm_delta_correlation
0,2024-03-08,2024-03-11,9350,6.659587,5.241532,5.058448,0.074545,2.475830,1.950422,-1.511878,...,7.947851,0.064670,1.200973,0.847951,-0.646126,1.323909,1.009280,-0.935654,0.055489,0.996971
1,2024-03-11,2024-03-12,9014,9.760928,7.744918,7.230043,0.020856,3.016337,2.762689,-2.718986,...,12.636815,0.032275,3.430437,3.207325,-3.207325,0.525617,0.388304,-0.201071,0.057634,0.996753
2,2024-03-12,2024-03-13,9001,7.143200,5.626863,4.123984,0.051105,1.256858,1.028806,-0.878062,...,5.586019,0.055288,1.140895,0.916533,-0.908145,1.518453,1.378353,-1.378347,0.051999,0.996907
3,2024-03-13,2024-03-14,8781,5.796688,4.547357,4.714147,0.101355,2.908517,2.604244,0.217395,...,7.895190,0.054719,2.263150,2.006643,1.539505,1.633431,1.498804,0.841765,0.052353,0.997057
4,2024-03-14,2024-03-15,9363,4.216070,3.329680,4.779193,0.295525,2.050136,1.744027,1.432095,...,8.711151,0.037124,1.834606,1.579049,1.548091,0.669306,0.532054,-0.243718,0.057929,0.997194
5,2024-03-15,2024-03-18,9178,6.459276,5.030825,5.395251,0.082480,2.277148,2.140766,-2.129348,...,9.083786,0.071704,2.264490,2.168418,-2.168418,0.574983,0.444559,-0.370135,0.059615,0.997281
6,2024-03-18,2024-03-19,9454,8.718397,6.739395,5.150226,0.028771,2.723518,2.216493,-1.339353,...,7.365064,0.061089,2.713020,2.301790,-2.301692,1.217099,0.965505,-0.746558,0.057984,0.997172
7,2024-03-19,2024-03-20,8781,7.184809,5.806411,7.346346,0.089284,4.886888,3.989347,-3.412705,...,13.300190,0.037149,2.125706,1.854075,-1.819687,1.621243,1.404857,0.466957,0.054398,0.996753
8,2024-03-20,2024-03-21,8904,8.057531,6.368274,5.665878,0.028976,2.431286,2.064771,0.166314,...,8.621218,0.036336,1.522318,1.327317,-0.983559,1.073490,0.773970,-0.149355,0.053914,0.996860
9,2024-03-21,2024-03-22,9601,7.900434,6.105467,4.089757,0.077596,1.225176,0.976085,-0.293995,...,4.678671,0.165476,0.912750,0.696000,-0.673779,1.153568,1.008765,-1.006807,0.050462,0.997012
10,2024-03-22,2024-03-25,9708,5.378519,4.109081,3.615869,0.097136,4.088520,3.317787,-2.040668,...,5.221006,0.130941,1.826470,1.318476,-0.541685,1.963240,1.433072,-1.266816,0.051427,0.996662
11,2024-03-25,2024-03-26,9512,6.473656,5.322388,4.831972,0.050673,2.004562,1.608853,-0.185429,...,6.885074,0.063463,1.158446,0.843900,-0.831355,1.855083,1.529094,-1.528996,0.053408,0.996675
12,2024-03-26,2024-03-27,9119,8.570907,6.955750,8.278756,0.085755,3.303027,2.790170,-2.361246,...,14.935846,0.074405,1.777284,1.613061,-1.496131,1.427152,1.316710,0.610439,0.053168,0.995993
13,2024-03-27,2024-03-28,9202,8.436116,6.787485,6.537939,0.022060,2.068840,1.566768,0.911955,...,10.076698,0.038974,0.619159,0.421374,0.042410,0.741051,0.572245,0.319141,0.052779,0.996295

In [7]:
from pathlib import Path
import zipfile

ROOT = Path.cwd()
OUT = ROOT / "v7_cpu_final_confirmation_results.zip"

folders = [
    sp.RUN_ROOT / "frozen_test_capped15_endpoint",
    sp.RUN_ROOT / "frozen_test_capped15_endpoint_eval400k",
]

with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as z:
    for folder in folders:
        if not folder.exists():
            print("Missing:", folder)
            continue

        for p in folder.rglob("*"):
            if p.is_file():
                z.write(
                    p,
                    arcname=str(
                        Path(folder.name) / p.relative_to(folder)
                    )
                )

print("Created:", OUT)
print("Size MB:", round(OUT.stat().st_size / 1024**2, 1))

Created: c:\Users\Startklar\ICL\NDEs\Codes\NSDE\GPT_NSDE_work\v7_long_run_workspace\v7_cpu_final_confirmation_results.zip
Size MB: 40.8